scaleway/terraform-provider-scaleway

- website/docs/r/security_group_rule.html.markdown
- website/docs/r/server.html.markdown
- website/docs/r/volume.html.markdown
working on https://github.com/nicolai86/terraform-tools showed
that the documentation is not up 2 date. this PR aims at adding the previously
undocumented attributes
> chore(docs): add documentation for undocumented attributes

- README.md
Must be updated to prevent build fail.
> Update package names in readme

- website/docs/index.html.markdown
The example talks about the C2S which isn't an ARM server ;)
> Fix example list

- scaleway/data_source_image.go
> sort images in a descending way

- scaleway/data_source_image_test.go
> fix: TestAccScalewayDataSourceImage_Filtered

- go.sum
- scaleway/config.go
- scaleway/provider.go
- scaleway/sweeper_test.go
> refactor: rename config field with new name convention

- scaleway/config.go
- scaleway/provider.go
> refactor: provider schema

- vendor/github.com/scaleway/scaleway-sdk-go/scw/client.go
- vendor/github.com/scaleway/scaleway-sdk-go/scw/client_option.go
- vendor/github.com/scaleway/scaleway-sdk-go/scw/version.go
- vendor/modules.txt
There seem to be some files which were probably accidentally omitted from vendoring.
This PR is just a result of `go mod vendor`.
> go mod vendor

- scaleway/provider.go
Since default function on 'organization' always returned a value if you set a 'project_id' it always showed the the 'deprecated warning'.
> fix: removed defaultfunc from 'organization' to supress useless warnings

- scaleway/provider.go
Since default function on 'token' always returned a value if you set a 'secret_key' it always showed the the 'deprecated warning'.
> fix: removed defaultfunc from 'token' to supress useless warnings

- scaleway/helpers.go
- scaleway/provider.go
- scaleway/validation.go
* feat: validation func for UUID
* feat: validation func for zone
* feat: validation func for region
* feat: default func for random name
> feat: validation and defaut func

- scaleway/resource_compute_instance_security_group.go
- scaleway/resource_compute_instance_security_group_test.go
> feat: security_group without port

- scaleway/validation.go
> Fix missing Sprintf in validation

- scaleway/resource_compute_instance_server.go
The value of security_group_id can be a zoned ID instead of being a regular uuid
> Try to parse the value security_group_id as a zoned ID 

- scaleway/resource_instance_server.go
- scaleway/resource_instance_server_test.go
This will allow remote exec to work by default
> fix: set dynamic IP by default

- go.mod
- go.sum
- scaleway/helpers_account.go
- scaleway/provider.go
- scaleway/resource_account_ssh_key_test.go
- scaleway/resource_account_ssk_key.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/account/v2alpha1/account_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/instance_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/server_utils.go
- vendor/github.com/scaleway/scaleway-sdk-go/internal/uuid/uuid.go
- vendor/modules.txt
- website/docs/r/account_ssk_key.html.markdown
- website/docs/r/ssh_key.html.markdown
- website/scaleway.erb
> feat: add scaleway_account_ssh_key

- website/docs/guides/regions_and_zones.html.markdown
> doc: fix API zones names

- scaleway/helpers.go
> fix: errors code check

- scaleway/helpers_k8s.go
- scaleway/provider.go
- scaleway/resource_k8s_cluster_beta.go
- scaleway/resource_k8s_cluster_beta_test.go
- scaleway/resource_k8s_pool_beta.go
- scaleway/resource_k8s_pool_beta_test.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/k8s/v1beta3/k8s_helpers.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/k8s/v1beta3/k8s_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/k8s/v1beta3/kubeconfig.go
> feat: k8s resource

- scaleway/resource_k8s_cluster_beta.go
- scaleway/resource_k8s_cluster_beta_test.go
- scaleway/resource_k8s_pool_beta.go
- scaleway/resource_k8s_pool_beta_test.go
> feat(k8s): add autohealing to pools

- scaleway/resource_k8s_cluster_beta.go
> fix(k8s): add missing placement group ID

- website/docs/r/k8s_cluster_beta.html.markdown
- website/docs/r/k8s_pool_beta.html.markdown
- website/scaleway.erb
> feat(k8s): add documentation

- website/docs/r/instance_security_group.html.markdown
> doc: add sg example with for_each

- website/docs/guides/migration_guide_v2.html.markdown
> doc(account): add scaleway_ssh_key renaming

- website/docs/r/k8s_cluster_beta.html.markdown
> fix: typos in k8s doc

- scaleway/resource_ip.go
> fix(ip): handle 403 error as a 404 in read function

- scaleway/resource_k8s_cluster_beta.go
> fix(k8s): default pool error

- scaleway/resource_k8s_cluster_beta.go
- scaleway/resource_k8s_pool_beta.go
> fix(k8s): handle regional IDs properly

- scaleway/resource_k8s_cluster_beta_test.go
- scaleway/resource_k8s_pool_beta_test.go
> test(k8s): add test for placement group

- scaleway/helpers.go
- scaleway/resource_k8s_cluster_beta.go
- scaleway/resource_k8s_pool_beta.go
> test(k8s): fix placement group test

- go.mod
- go.sum
- scaleway/helpers_rdb.go
- scaleway/provider.go
- scaleway/resource_lb_beta.go
- scaleway/resource_rdb_instance_beta.go
- scaleway/resource_rdb_instance_beta_test.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/instance_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/rdb/v1/rdb_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/rdb/v1/rdb_utils.go
- vendor/modules.txt
- website/docs/r/lb_beta.html.markdown
- website/docs/r/rdb_instance_beta.html.markdown
- website/scaleway.erb
> feat(rdb): instance resource

- website/docs/r/lb_backend_beta.html.markdown
- website/docs/r/lb_frontend_beta.html.markdown
> doc(lb): fix small typos

- scaleway/provider.go
> fix(core): handle config bootstrap error

- scaleway/resource_lb_backend_beta.go
- scaleway/resource_lb_backend_beta_test.go
> fix(lb): add missing health_check_delay

- scaleway/helpers.go
> fix(helpers): remove extra quotes on flatten

- scaleway/resource_rdb_instance_beta_test.go
The concurrency issue has been fixed 🎉
> fix: enable rdb acceptance tests

- scaleway/resource_instance_ip.go
- scaleway/resource_instance_ip_test.go
- scaleway/resource_instance_server.go
- scaleway/resource_instance_server_test.go
- website/docs/r/instance_ip.html.markdown
- website/docs/r/instance_server.html.markdown
> feat(instance): move ip attachement to server

- scaleway/resource_k8s_cluster_beta.go
- website/docs/r/k8s_cluster_beta.html.markdown
> fix(k8s): fix default ingress

- website/docs/d/marketplace_image_beta.html.markdown
**"C'est trop de labal."**
I only raised this PR for the pun.
> style: `labal` -> `label`

- website/docs/r/instance_server.html.markdown
> fix(doc): additional volume with block type

- go.mod
- go.sum
- vendor/github.com/scaleway/scaleway-sdk-go/api/baremetal/v1alpha1/baremetal_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/instance_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/security_group_utils.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/server_utils.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/k8s/v1beta4/k8s_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/rdb/v1/rdb_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/scw/custom_types.go
- vendor/github.com/scaleway/scaleway-sdk-go/scw/errors.go
- vendor/modules.txt
> chore(core): bump sdk version

- go.mod
- go.sum
- vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/instance_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/instance_utils.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/k8s/v1beta4/k8s_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/lb/v1/lb_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/scw/custom_types.go
- vendor/github.com/scaleway/scaleway-sdk-go/scw/errors.go
- vendor/modules.txt
> chore(vendor): bump sdk version

- scaleway/resource_k8s_cluster_beta.go
- website/docs/r/k8s_cluster_beta.html.markdown
> fix(k8s): version is required

- go.mod
- go.sum
- scaleway/resource_instance_server.go
- scaleway/resource_instance_server_test.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/instance_sdk.go
- vendor/modules.txt
- website/docs/r/instance_server.html.markdown
> feat(instance): support deprecated instance types

- website/docs/d/marketplace_image_beta.html.markdown
> doc: fix typo in marketplace example

- scaleway/provider.go
> fix(registry): add registry back to list of resources

- website/docs/r/instance_server.html.markdown
"disable_dynamic_ip": [REMOVED] Removed in favor of enable_dynamic_ip.
> Fix argument disable_dynamic_ip

- scaleway/resource_k8s_cluster_beta.go
- website/docs/r/k8s_cluster_beta.html.markdown
> fix(k8s): wait for default pool on pool replacement

- website/docs/r/k8s_cluster_beta.html.markdown
> doc(k8s): fix third level list on nodes

- scaleway/data_source_helpers.go
- scaleway/data_source_registry_image_beta.go
- scaleway/data_source_registry_image_beta_test.go
- scaleway/data_source_registry_namespace_beta.go
- scaleway/helpers_registry.go
- scaleway/provider.go
- scaleway/resource_registry_namespace_beta.go
- scaleway/resource_registry_namespace_beta_test.go
- website/docs/d/registry_image_beta.html.markdown
- website/docs/d/registry_namespace_beta.html.markdown
- website/scaleway.erb
> feat(registry): add image data source

- website/docs/r/instance_security_group.html.markdown
Add documentation and example for port_range usage in instance_security_group
> doc(instance): updated instance_security_group with port_range

- scaleway/resource_k8s_cluster_beta.go
- scaleway/resource_k8s_cluster_beta_test.go
- scaleway/resource_k8s_pool_beta.go
- scaleway/resource_k8s_pool_beta_test.go
- website/docs/r/k8s_cluster_beta.html.markdown
- website/docs/r/k8s_pool_beta.html.markdown
> feat(k8s): add tags to pools

- website/docs/r/k8s_cluster_beta.html.markdown
> doc(k8s): fix typo in admission_plugins argument

- scaleway/resource_instance_server.go
> fix(instance): fix error message on image get

- .travis.yml
- go.mod
- go.sum
- scaleway/helpers_k8s.go
- scaleway/resource_k8s_cluster_beta.go
- scaleway/resource_k8s_cluster_beta_test.go
- scaleway/resource_k8s_pool_beta.go
- scaleway/resource_k8s_pool_beta_test.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/account/v2alpha1/account_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/baremetal/v1alpha1/baremetal_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/baremetal/v1alpha1/server_utils.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/instance_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/k8s/v1/k8s_helpers.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/k8s/v1/k8s_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/k8s/v1/kubeconfig.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/lb/v1/lb_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/marketplace/v1/marketplace_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/rdb/v1/rdb_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/registry/v1/registry_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/scw/config.go
- vendor/github.com/scaleway/scaleway-sdk-go/scw/convert.go
- vendor/github.com/scaleway/scaleway-sdk-go/scw/env.go
- vendor/github.com/scaleway/scaleway-sdk-go/scw/errors.go
- vendor/github.com/scaleway/scaleway-sdk-go/scw/path.go
- vendor/github.com/scaleway/scaleway-sdk-go/scw/version.go
- vendor/modules.txt
- website/docs/r/k8s_cluster_beta.html.markdown
- website/docs/r/k8s_pool_beta.html.markdown
> feat(k8s): add v1 and deprecate beta

- scaleway/resource_account_ssh_key_test.go
- scaleway/resource_baremetal_server_beta_test.go
- scaleway/resource_instance_ip_test.go
- scaleway/resource_instance_placement_group_test.go
- scaleway/resource_instance_security_group_test.go
- scaleway/resource_instance_server_test.go
- scaleway/resource_instance_volume_test.go
- scaleway/resource_k8s_cluster_beta_test.go
- scaleway/resource_lb_beta_test.go
- scaleway/resource_rdb_instance_beta_test.go
- scaleway/resource_registry_namespace_beta_test.go
- scaleway/sweeper_test.go
> feat(sweeper): add missing sweepers

- scaleway/provider.go
- scaleway/resource_lb_beta.go
- scaleway/resource_lb_beta_test.go
- scaleway/resource_lb_ip_beta.go
- scaleway/resource_lb_ip_beta_test.go
- website/docs/r/lb_beta.html.markdown
- website/docs/r/lb_ip_beta.html.markdown
> feat(lb): add IP resource

- scaleway/helpers.go
- scaleway/resource_instance_server.go
- scaleway/resource_instance_server_test.go
> feat(instance): use RegionalID for server

- scaleway/helpers_baremetal.go
> fix(baremetal): fix missing ips from computed

- scaleway/helpers_baremetal.go
- scaleway/resource_baremetal_server_beta.go
- website/docs/r/baremetal_server_beta.html.markdown
> feat(baremetal): add ip version to ips output

- scaleway/helpers_k8s.go
- scaleway/resource_k8s_cluster_beta.go
- scaleway/resource_k8s_cluster_beta_test.go
- website/docs/r/k8s_cluster_beta.html.markdown
> feat(k8s): use minor version on autoupgrades

- scaleway/sweeper_test.go
> test(sweeper): ignore errors

- scaleway/resource_lb_backend_beta_test.go
- scaleway/resource_lb_beta_test.go
- scaleway/resource_lb_certificate_beta_test.go
- scaleway/resource_lb_frontend_beta_test.go
> fix(lb): fix tests not passing

- scaleway/resource_k8s_cluster_beta.go
- scaleway/resource_k8s_cluster_beta_test.go
- scaleway/resource_k8s_pool_beta_test.go
> test(k8s): get the latest versions for the tests from the API

- website/docs/r/k8s_cluster_beta.html.markdown
> fix(k8s): fix doc formatting

- website/docs/r/lb_beta.html.markdown
- website/scaleway.erb
> doc: fix missing lbip in navbar and fix lb display

- scaleway/resource_instance_security_group.go
- scaleway/resource_instance_security_group_rules_test.go
> fix(instance): fix ipv6 security rule validation

- website/docs/r/k8s_cluster_beta.html.markdown
- website/docs/r/k8s_pool_beta.html.markdown
> doc(k8s): some fixes

- scaleway/resource_instance_security_group.go
- website/docs/r/instance_security_group.html.markdown
> feat(instance): add stateful field to security group

- website/docs/r/k8s_cluster_beta.html.markdown
> doc(k8s): specify usage with kubernetes provider

- go.mod
- go.sum
- scaleway/helpers_instance.go
- scaleway/resource_account_ssh_key.go
- scaleway/resource_baremetal_server.go
- scaleway/resource_instance_volume.go
- scaleway/resource_lb_beta.go
- scaleway/resource_rdb_instance_beta.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/account/v2alpha1/account_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/baremetal/v1/server_utils.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/instance_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/server_utils.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/snapshot_utils.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/k8s/v1/k8s_helpers.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/k8s/v1/k8s_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/lb/v1/lb_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/lb/v1/lb_utils.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/rdb/v1/rdb_sdk.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/rdb/v1/rdb_utils.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/registry/v1/image_utils.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/registry/v1/registry_utils.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/registry/v1/tag_utils.go
- vendor/github.com/scaleway/scaleway-sdk-go/scw/config.go
- vendor/github.com/scaleway/scaleway-sdk-go/scw/env.go
- vendor/github.com/scaleway/scaleway-sdk-go/scw/errors.go
- vendor/github.com/scaleway/scaleway-sdk-go/scw/path.go
- vendor/modules.txt
Signed-off-by: Clément Decoodt <cdecoodt@online.net>
There are some breaking changes since last time, these are fixed in the same commit to avoid a non-compilable commit.
> chore(vendor): Update scaleway go sdk to latest version

- scaleway/config.go
- scaleway/provider.go
> feat: custom URL and custom regions/zones

- scaleway/helpers_lb.go
- scaleway/resource_lb_backend_beta.go
- scaleway/resource_lb_backend_beta_test.go
- website/docs/r/lb_backend_beta.html.markdown
> feat(lb): replace send_proxy_v2 by proxy_protocol

- .github/workflows/release.yml
> fix(action): correctly escape GPG passphrase

- scaleway/resource_k8s_cluster_beta.go
> fix(k8s): fix always present auto upgrade requets on update

- docs/resources/k8s_cluster_beta.md
- scaleway/resource_k8s_cluster_beta.go
> feat(k8s): add delete_additional_resources

- docs/index.md
> doc: add terraform 0.13 block to example

- scaleway/resource_lb_backend_beta.go
> fix(lb): fix proxy protocol default value

- .github/workflows/release.yml
- go.mod
- go.sum
- scaleway/data_source_instance_image.go
- scaleway/resource_baremetal_server.go
- scaleway/resource_instance_placement_group.go
- scaleway/resource_instance_security_group.go
- scaleway/resource_instance_server.go
- scaleway/resource_instance_volume.go
- scaleway/resource_k8s_cluster_beta.go
- scaleway/resource_lb_backend_beta.go
- scaleway/resource_lb_beta.go
- scaleway/resource_lb_certificate_beta.go
- scaleway/resource_lb_frontend_beta.go
- scaleway/resource_lb_ip_beta.go
- scaleway/resource_rdb_instance_beta.go
- scaleway/resource_registry_namespace_beta.go
> chore: bump SDK version

- scaleway/resource_baremetal_server.go
- scaleway/resource_k8s_cluster_beta.go
- scaleway/resource_lb_beta.go
- scaleway/resource_lb_beta_test.go
- scaleway/resource_lb_ip_beta.go
- scaleway/resource_lb_ip_beta_test.go
- scaleway/resource_rdb_instance_beta.go
- scaleway/resource_registry_namespace_beta.go
> chore: fix bugs

- scaleway/resource_instance_placement_group.go
- scaleway/resource_instance_security_group.go
- scaleway/resource_instance_server.go
- scaleway/resource_instance_volume.go
> fix(instance): use expandStringPtr for Organization

- scaleway/resource_instance_server_test.go
- scaleway/testdata/instance-server-user-data-with-cloud-init-at-start.cassette.yaml
- scaleway/testdata/instance-server-user-data-without-cloud-init-at-start.cassette.yaml
https://github.com/hashicorp/terraform-plugin-sdk/issues/595
https://github.com/hashicorp/terraform-plugin-sdk/pull/614/files
Historic problem about using hash value in TypeSet: https://github.com/hashicorp/terraform-plugin-sdk/issues/196
The order of the key in the state is deterministic because of https://github.com/hashicorp/terraform-plugin-sdk/blob/master/helper/schema/set.go#L268
> fix(instance): fix user data tests

- docs/data-sources/k8s_cluster.md
- docs/data-sources/k8s_pool.md
- scaleway/data_source_k8s_cluster.go
- scaleway/data_source_k8s_cluster_test.go
- scaleway/data_source_k8s_pool.go
- scaleway/data_source_k8s_pool_test.go
- scaleway/provider.go
- scaleway/testdata/data-source-k8s-cluster-basic.cassette.yaml
- scaleway/testdata/data-source-k8s-pool-basic.cassette.yaml
> feat(k8s): add cluster and pool datasource

- docs/resources/iot_device.md
- scaleway/helpers.go
- scaleway/provider.go
- scaleway/resource_iot_device.go
- scaleway/resource_iot_device_test.go
- scaleway/testdata/iot-device-minimal.cassette.yaml
Based on #503 
This Pull Request adds IoT Hub Devices support in terraform.
> Iot hub devices implementation

- docs/resources/k8s_cluster.md
- docs/resources/k8s_pool.md
- go.mod
- go.sum
- scaleway/helpers_k8s.go
- scaleway/resource_k8s_cluster.go
- scaleway/resource_k8s_cluster_test.go
- scaleway/resource_k8s_pool.go
- scaleway/resource_k8s_pool_test.go
- scaleway/testdata/k8s-cluster-auto-upgrade.cassette.yaml
- scaleway/testdata/k8s-cluster-autoscaling.cassette.yaml
- scaleway/testdata/k8s-cluster-basic.cassette.yaml
- scaleway/testdata/k8s-cluster-ingress-dashboard.cassette.yaml
- scaleway/testdata/k8s-cluster-oidc.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-basic.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-kubelet-args.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-placement-group.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-upgrade-policy.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-wait.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-zone.cassette.yaml
> feat(k8s): add new features

- scaleway/data_source_marketplace_image_test.go
- scaleway/testdata/data-source-marketplace-image-basic.cassette.yaml
```bash
TF_ACC=1 go test -a  ./scaleway -v -run=TestAccScalewayDataSourceMarketplaceImage_Basic -timeout=20m -parallel=5
=== RUN   TestAccScalewayDataSourceMarketplaceImage_Basic
=== PAUSE TestAccScalewayDataSourceMarketplaceImage_Basic
=== CONT  TestAccScalewayDataSourceMarketplaceImage_Basic
--- PASS: TestAccScalewayDataSourceMarketplaceImage_Basic (0.57s)
PASS
ok      github.com/scaleway/terraform-provider-scaleway/scaleway        0.578s
```
> test(marketplace/image): Sync image id with latest build

- scaleway/resource_apple_silicon_server_test.go
- scaleway/resource_baremetal_server_test.go
> test: skip Baremetal and AppleSilicon tests from automatic tests

- scaleway/data_source_registry_namespace_test.go
- scaleway/resource_registry_namespace_test.go
- scaleway/testdata/data-source-registry-namespace-basic.cassette.yaml
- scaleway/testdata/registry-namespace-basic.cassette.yaml
> feat(registry): fix test suite

- .github/workflows/acceptance-tests.yaml
- .github/workflows/nightly.yml
- feat(workflow): increase timeout
> chore: increase acceptance test timeout

- scaleway/resource_instance_server_test.go
- scaleway/testdata/instance-server-enterprise.cassette.yaml
- change zone for test entreprise
> fix(instance): server entreprise not available on fr-par-1

- scaleway/resource_iot_hub_test.go
> fix(iot): refactor sweeper to use sweepRegions

- scaleway/data_source_marketplace_image_test.go
- scaleway/testdata/data-source-marketplace-image-basic.cassette.yaml
- remove useless test ID
- add check label
> fix(marketplace): remove fixed ID

- scaleway/resource_lb_certificate.go
- scaleway/resource_lb_ip.go
- scaleway/resource_lb_ip_test.go
- scaleway/testdata/data-source-lb-basic.cassette.yaml
- scaleway/testdata/data-source-lbip-basic.cassette.yaml
- scaleway/testdata/lb-backend-basic.cassette.yaml
- scaleway/testdata/lb-backend-health-check.cassette.yaml
- scaleway/testdata/lb-certificate-basic.cassette.yaml
- scaleway/testdata/lb-frontend-basic.cassette.yaml
- scaleway/testdata/lb-route-basic.cassette.yaml
- scaleway/testdata/lbacl-basic.cassette.yaml
- scaleway/testdata/lbip-basic.cassette.yaml
- scaleway/testdata/lblb-with-ip.cassette.yaml
* Add check state on post destroy
* fix update name on certificate lb
* Rewrite cassettes with new queries
> fix(lb): check certificate update & lb state post destroy check

- scaleway/resource_vpc_private_network.go
- scaleway/resource_vpc_private_network_test.go
- scaleway/testdata/vpc-private-network-basic.cassette.yaml
Related to [issue](https://github.com/scaleway/terraform-provider-scaleway/issues/986)
> Fix(vpc-private-network): Add flag computed to name on schema

- scaleway/helpers_instance.go
- scaleway/resource_instance_server_test.go
- scaleway/testdata/instance-server-private-network.cassette.yaml
> Fix(instance): check private network and add test case

- docs/resources/vpc_gateway_network.md
Add configuration to allow the instances (in a private vpc) to access internet by the gateway
> improve(doc): add configuration to allow the instances to access internet

- docs/resources/instance_security_group_rules.md
> doc(instance_security_group_rules): add rule port_range field doc

- scaleway/helpers.go
- scaleway/resource_vpc_public_gateway_dhcp.go
Added an helper to get boolean from schema if it exists
> fix: vpc optional booleans

- scaleway/testdata/data-source-domain-record-basic.cassette.yaml
- scaleway/testdata/data-source-domain-zone-basic.cassette.yaml
- scaleway/testdata/domain-record-basic.cassette.yaml
- scaleway/testdata/domain-record-basic2.cassette.yaml
- scaleway/testdata/domain-record-geo-ip.cassette.yaml
- scaleway/testdata/domain-record-http-service.cassette.yaml
- scaleway/testdata/domain-record-view.cassette.yaml
- scaleway/testdata/domain-record-weighted.cassette.yaml
- scaleway/testdata/domain-zone-basic.cassette.yaml
- scaleway/testdata/instance-ip-reverse-dns-basic.cassette.yaml
- scaleway/testdata/vpc-public-gateway-ip-basic.cassette.yaml
This should fix tests failings randomly on CI
Pattern used : `TestAccScaleway(DataSource)?DomainRecord.*|TestAccScaleway(DataSource)?DomainZone.*|TestAccScalewayVPCPublicGatewayIP_Basic|TestAccScalewayInstanceIPReverseDns_Basic`
> test: update cassettes of all tests using dns

- scaleway/testdata/domain-record-basic.cassette.yaml
> test(domain): update basic test cassette

- docs/resources/instance_server.md
- scaleway/helpers_instance.go
- scaleway/resource_instance_server.go
- scaleway/resource_instance_server_test.go
- scaleway/testdata/instance-server-root-volume-id.cassette.yaml
>  feat(instance): allows setting root_volume id 

- scaleway/resource_instance_image_test.go
- scaleway/resource_instance_snapshot_test.go
- scaleway/resource_vpc_public_gateway_dhcp_test.go
> test: add missing sweepers

- docs/resources/redis_cluster.md
- scaleway/resource_redis_cluster.go
- scaleway/resource_redis_cluster_test.go
- scaleway/testdata/redis-cluster-acl.cassette.yaml
- scaleway/testdata/redis-cluster-basic.cassette.yaml
- scaleway/testdata/redis-cluster-certificate.cassette.yaml
- scaleway/testdata/redis-cluster-endpoints-cluster-mode.cassette.yaml
- scaleway/testdata/redis-cluster-endpoints-standalone.cassette.yaml
- scaleway/testdata/redis-cluster-migrate.cassette.yaml
- scaleway/testdata/redis-cluster-no-certificate.cassette.yaml
- scaleway/testdata/redis-cluster-settings.cassette.yaml
> feat(redis): add certificate

- scaleway/resource_redis_cluster.go
> fix(redis): ignore case on type diff

- docs/resources/k8s_cluster.md
- docs/resources/k8s_pool.md
resolve https://github.com/scaleway/terraform-provider-scaleway/issues/1411
> doc(k8s): 'external' node-type for kapsule pool

- scaleway/resource_function.go
- scaleway/resource_function_cron_test.go
- scaleway/testdata/function-cron-basic.cassette.yaml
- scaleway/testdata/function-cron-with-args.cassette.yaml
> Function cron tests fix

- scaleway/resource_container.go
> fix(container): set env variables to computed

- scaleway/helpers_domain.go
- scaleway/resource_domain_record.go
- scaleway/resource_domain_record_test.go
- scaleway/testdata/domain-record-cname.cassette.yaml
> fix(domain_record): cname domain creation

- docs/resources/function.md
- scaleway/resource_function.go
- scaleway/resource_function_test.go
- scaleway/testdata/function-timeout.cassette.yaml
> fix(function): timeout type

- scaleway/resource_iam_api_key.go
- scaleway/resource_iam_api_key_test.go
- scaleway/testdata/iam-api-key-expires.cassette.yaml
- scaleway/testdata/iam-api-key-no-update.cassette.yaml
- scaleway/testdata/iam-api-key-with-application.cassette.yaml
- scaleway/testdata/iam-api-key-with-user.cassette.yaml
> fix(iam_api_key): set secret_key on create

- scaleway/resource_domain_record_test.go
- scaleway/testdata/domain-record-cname.cassette.yaml
Test had the same dns zone as basic test, it failed under certain conditions in nightly tests
> test(domain_record): change cname test dns zone

- scaleway/resource_rdb_instance.go
> fix(rdb): private network attachement with return 404

- scaleway/retryable_transport.go
> fix(provider): handle http error on failed retries

- docs/resources/container_token.md
- scaleway/helpers.go
- scaleway/provider.go
- scaleway/resource_container_token.go
- scaleway/resource_container_token_test.go
- scaleway/testdata/container-token-basic.cassette.yaml
> feat(container): add container_token resource

- scaleway/resource_container_token.go
> fix(container_token): set token to state only on create

- .github/workflows/acceptance-tests.yaml
- .github/workflows/nightly.yml
- TESTING.md
- scaleway/resource_container_test.go
- scaleway/testdata/container-with-img.cassette.yaml
> tests(container): enable with image test and change image 

- scaleway/resource_object_bucket_policy_test.go
- scaleway/testdata/bucket-policy-basic.cassette.yaml
> test(object-policy): enable bucket policy cassettes

- docs/data-sources/instance_snapshot.md
- scaleway/data_source_instance_snapshot.go
- scaleway/data_source_instance_snapshot_test.go
- scaleway/provider.go
- scaleway/testdata/data-source-instance-snapshot-basic.cassette.yaml
> feat(instance): add snapshot data source

- scaleway/resource_instance_private_nic.go
- scaleway/testdata/instance-private-nic-basic.cassette.yaml
> fix(instance_nic): wait for instance before creating private_nic

- docs/resources/container.md
- docs/resources/container_domain.md
- scaleway/helpers_container.go
- scaleway/provider.go
- scaleway/resource_container_domain.go
- scaleway/resource_container_domain_test.go
- scaleway/testdata/container-domain-basic.cassette.yaml
> feat(container): add domain

- docs/data-sources/vpc_public_gateway.md
- scaleway/data_source_vpc_public_gateway.go
- scaleway/data_source_vpc_public_gateway_test.go
- scaleway/resource_vpc_public_gateway_test.go
- scaleway/testdata/data-source-vpc-public-gateway-basic.cassette.yaml
- scaleway/testdata/vpc-public-gateway-basic.cassette.yaml
> Fix(vpcgw): add zone option to  datasource vpcgw

- docs/resources/iam_api_key.md
> fix(iam) add missing attribute

- scaleway/resource_account_project.go
- scaleway/resource_function_namespace.go
- scaleway/resource_iam_group.go
- scaleway/resource_iam_policy.go
> fix: generated names format with an extra dash

- scaleway/provider_test.go
> feat(provider): anonymize sensitive fields in cassettes

- scaleway/provider_test.go
- scaleway/retryable_transport.go
> tests: remove wait on retry when using cassettes

- scaleway/helpers.go
- scaleway/resource_lb.go
- scaleway/resource_lb_test.go
- scaleway/testdata/lblb-different-locality-ipid.cassette.yaml
> feat(provider): add helper to validate locality IDs with resource ID

- scaleway/helpers_container.go
- scaleway/resource_container.go
- scaleway/resource_container_test.go
- scaleway/resource_container_token_test.go
- scaleway/resource_function.go
- scaleway/resource_function_test.go
- scaleway/resource_function_token_test.go
- scaleway/testdata/container-basic.cassette.yaml
- scaleway/testdata/container-cron-basic.cassette.yaml
- scaleway/testdata/container-cron-with-multi-args.cassette.yaml
- scaleway/testdata/container-domain-basic.cassette.yaml
- scaleway/testdata/container-env.cassette.yaml
- scaleway/testdata/container-http-option.cassette.yaml
- scaleway/testdata/container-token-basic.cassette.yaml
- scaleway/testdata/container-with-img.cassette.yaml
- scaleway/testdata/data-source-container-basic.cassette.yaml
- scaleway/testdata/data-source-function-basic.cassette.yaml
- scaleway/testdata/function-basic.cassette.yaml
- scaleway/testdata/function-cron-basic.cassette.yaml
- scaleway/testdata/function-cron-with-args.cassette.yaml
- scaleway/testdata/function-deploy.cassette.yaml
- scaleway/testdata/function-domain-basic.cassette.yaml
- scaleway/testdata/function-environment-variables.cassette.yaml
- scaleway/testdata/function-http-option.cassette.yaml
- scaleway/testdata/function-no-name.cassette.yaml
- scaleway/testdata/function-timeout.cassette.yaml
- scaleway/testdata/function-token-basic.cassette.yaml
- scaleway/testdata/function-upload.cassette.yaml
> feat(serverless): add http_option attribute

- scaleway/resource_object_bucket.go
- scaleway/resource_object_bucket_test.go
- scaleway/testdata/object-bucket-basic.cassette.yaml
- scaleway/testdata/object-bucket-cors-delete.cassette.yaml
- scaleway/testdata/object-bucket-cors-update.cassette.yaml
- scaleway/testdata/object-bucket-destroy-force.cassette.yaml
> feat(object): versioning should be enabled with object locking

- scaleway/resource_rdb_database.go
- scaleway/resource_rdb_privilege.go
- scaleway/resource_rdb_user.go
> fix(rdb): 404 check on read resources

- scaleway/helpers.go
- scaleway/helpers_test.go
- scaleway/resource_object_test.go
- scaleway/testdata/object-basic.cassette.yaml
> fix(object): handles nested id

- docs/resources/rdb_user.md
- scaleway/resource_rdb_user.go
> fix(rdb): check user exist

- .github/workflows/nightly.yml
> ci: trigger webhook on nightly tests failure

- scaleway/provider_test.go
- scaleway/resource_iam_policy_test.go
- scaleway/testdata/iam-policy-basic.cassette.yaml
- scaleway/testdata/iam-policy-change-linked-entity.cassette.yaml
- scaleway/testdata/iam-policy-change-permissions.cassette.yaml
- scaleway/testdata/iam-policy-change-rule-principal.cassette.yaml
- scaleway/testdata/iam-policy-no-update.cassette.yaml
- scaleway/testdata/iam-policy-project-id.cassette.yaml
> fix(iam):  enhancement policy with fake project manager

- go.mod
- go.sum
- scaleway/data_source_cockpit.go
- scaleway/data_source_cockpit_test.go
- scaleway/helpers_cockpit.go
- scaleway/provider.go
- scaleway/resource_cockpit.go
- scaleway/resource_cockpit_test.go
- scaleway/testdata/cockpit-basic.cassette.yaml
- scaleway/testdata/data-source-cockpit-basic.cassette.yaml
> feat(cockpit): implement resource and datasource

- scaleway/resource_k8s_cluster.go
> fix(k8s): kubeconfig is now sensitive

- docs/resources/cockpit_grafana_user.md
- scaleway/helpers_cockpit.go
- scaleway/provider.go
- scaleway/resource_cockpit_grafana_user.go
- scaleway/resource_cockpit_grafana_user_test.go
- scaleway/testdata/cockpit-grafana-user-basic.cassette.yaml
- scaleway/testdata/cockpit-grafana-user-non-existent-cockpit.cassette.yaml
- scaleway/testdata/cockpit-grafana-user-update.cassette.yaml
> feat(cockpit): implement grafana user resource

- docs/guides/multicloud_cluster_with_baremetal_servers.md
- docs/resources/k8s_cluster.md
Closes #1433
This guide shows how to add and run Elastic Metal servers as nodes in a multicloud cluster.
> doc(k8s): guide for using baremetal with Kosmos cluster

- docs/resources/object_bucket.md
- scaleway/helpers_object.go
- scaleway/testdata/bucket-policy-basic.cassette.yaml
- scaleway/testdata/data-source-object-storage-basic.cassette.yaml
- scaleway/testdata/data-source-object-storage-project-id-allowed.cassette.yaml
- scaleway/testdata/data-source-object-storage-project-id-forbidden.cassette.yaml
- scaleway/testdata/object-bucket-acl-basic.cassette.yaml
- scaleway/testdata/object-bucket-acl-grantee-with-owner.cassette.yaml
- scaleway/testdata/object-bucket-acl-grantee.cassette.yaml
- scaleway/testdata/object-bucket-basic.cassette.yaml
- scaleway/testdata/object-bucket-cors-delete.cassette.yaml
- scaleway/testdata/object-bucket-cors-update.cassette.yaml
- scaleway/testdata/object-bucket-destroy-force.cassette.yaml
- scaleway/testdata/object-bucket-lock-configuration-basic.cassette.yaml
- scaleway/testdata/object-bucket-lock-configuration-update.cassette.yaml
- scaleway/testdata/test-acc-object-bucket-website-configuration-basic.cassette.yaml
- scaleway/testdata/test-acc-object-bucket-website-configuration-update.cassette.yaml
- scaleway/testdata/test-acc-object-bucket-website-configuration-with-policy.cassette.yaml
> feat(object): allow importing bucket with a specific project id

- docs/resources/rdb_read_replica.md
- scaleway/resource_rdb_read_replica.go
- scaleway/resource_rdb_read_replica_test.go
> fix(rdb): read replica set

- scaleway/helpers.go
```
tags = ["foo", ""]
```
result as
```
[]any{"foo", nil}
```
> fix: empty strings in list being nil

- docs/resources/cockpit_token.md
> docs(cockpit): fix scopes example

- docs/resources/tem_domain.md
> doc(tem): Add informations regarding the new accept_tos attribute.

- scaleway/resource_function_token.go
> fix(function_token): set token only on create

- scaleway/helpers_instance.go
- scaleway/resource_instance_ip_reverse_dns.go
- scaleway/testdata/instance-ip-reverse-dns-basic.cassette.yaml
Local resolve may fail depending of the local network configuration.
Closes #1909
> fix(instance_ip_reverse_dns): retry update instead of resolving dns

- scaleway/data_source_account_project.go
> fix(account): project data source project not found

- docs/data-sources/vpc_private_network.md
- docs/resources/vpc_private_network.md
- scaleway/data_source_vpc_private_network_test.go
- scaleway/helpers_vpc.go
- scaleway/resource_vpc_private_network.go
- scaleway/resource_vpc_private_network_test.go
- scaleway/testdata/data-source-vpc-private-network-basic.cassette.yaml
- scaleway/testdata/vpc-private-network-basic.cassette.yaml
- scaleway/testdata/vpc-private-network-default-name.cassette.yaml
- scaleway/testdata/vpc-private-network-subnets.cassette.yaml
> feat(vpc): add subnets attribute in private_network resource (#1930)

- scaleway/helpers_container.go
- scaleway/resource_container.go
- scaleway/resource_container_test.go
- scaleway/testdata/container-basic.cassette.yaml
> fix(container): use cpu_limit

- scaleway/data_source_secret_version.go
> fix(secret-manager): encode data on data_source

- docs/resources/k8s_cluster.md
changing this field won't automatically recreate cluster linked commit 4ac9d10
> doc(k8s): private_network_id

- scaleway/data_source_container.go
- scaleway/data_source_container_namespace.go
- scaleway/data_source_function.go
- scaleway/data_source_function_namespace.go
- scaleway/data_source_helpers.go
- scaleway/data_source_iot_device.go
- scaleway/data_source_iot_hub.go
- scaleway/data_source_k8s_cluster.go
- scaleway/data_source_k8s_pool.go
- scaleway/data_source_rdb_acl.go
- scaleway/data_source_rdb_database.go
- scaleway/data_source_rdb_database_backup.go
- scaleway/data_source_rdb_instance.go
- scaleway/data_source_registry_image.go
- scaleway/data_source_registry_namespace.go
- scaleway/data_source_secret.go
- scaleway/data_source_tem_domain.go
- scaleway/data_source_vpc.go
- scaleway/data_source_webhosting_offer.go
> chore: refactor datasource regionalID helper

- docs/resources/object.md
- scaleway/resource_object.go
- scaleway/resource_object_test.go
- scaleway/testdata/object-by-content-base64.cassette.yaml
This PR follows #1997 and adds the possibility to create a file by non-base64-encoded content.
> feat(object): create object by string content

- docs/resources/k8s_cluster.md
- scaleway/resource_k8s_cluster.go
- scaleway/resource_k8s_cluster_test.go
- scaleway/resource_k8s_pool_test.go
- scaleway/testdata/data-source-k8s-cluster-basic.cassette.yaml
- scaleway/testdata/k8s-cluster-auto-upgrade.cassette.yaml
- scaleway/testdata/k8s-cluster-autoscaling.cassette.yaml
- scaleway/testdata/k8s-cluster-basic.cassette.yaml
- scaleway/testdata/k8s-cluster-multicloud.cassette.yaml
- scaleway/testdata/k8s-cluster-oidc.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-basic.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-kubelet-args.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-placement-group.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-private-network.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-size.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-upgrade-policy.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-wait.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-zone.cassette.yaml
- scaleway/testdata/k8s-cluster-private-network.cassette.yaml
The private networks used with Kapsule clusters are now regional (when they were zoned before).
> feat(k8s): Kapsule VPCs go from zoned to regional

- scaleway/helpers_k8s.go
- scaleway/resource_k8s_cluster.go
> feat(k8s): skip reading kubeconfig if unauthorized

- scaleway/resource_redis_cluster.go
> fix(redis): add computed to private network attribute

- docs/data-sources/ipam_ip.md
- scaleway/data_source_ipam_ip.go
- scaleway/data_source_ipam_ip_test.go
- scaleway/helpers_ipam.go
- scaleway/provider.go
- scaleway/testdata/data-source-ipamip-instance-lb.cassette.yaml
- scaleway/testdata/data-source-ipamip-instance.cassette.yaml
> feat(ipam): add ipam ip data source

- docs/resources/k8s_cluster.md
- go.mod
- go.sum
- scaleway/helpers.go
- scaleway/resource_k8s_cluster.go
- scaleway/resource_k8s_cluster_test.go
- scaleway/testdata/data-source-k8s-cluster-basic.cassette.yaml
- scaleway/testdata/k8s-cluster-auto-upgrade.cassette.yaml
- scaleway/testdata/k8s-cluster-autoscaling.cassette.yaml
- scaleway/testdata/k8s-cluster-basic.cassette.yaml
- scaleway/testdata/k8s-cluster-multicloud.cassette.yaml
- scaleway/testdata/k8s-cluster-oidc.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-basic.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-kubelet-args.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-placement-group.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-private-network.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-size.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-upgrade-policy.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-wait.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-zone.cassette.yaml
- scaleway/testdata/k8s-cluster-private-network.cassette.yaml
- scaleway/testdata/k8s-cluster-type-change.cassette.yaml
> feat(k8s): type change should migrate cluster when possible

- docs/data-sources/instance_ip.md
- docs/data-sources/instance_server.md
- docs/data-sources/instance_servers.md
- docs/resources/instance_ip.md
- docs/resources/instance_server.md
- scaleway/data_source_instance_servers.go
- scaleway/helpers_instance.go
- scaleway/helpers_k8s.go
- scaleway/resource_container_test.go
- scaleway/resource_instance_ip.go
- scaleway/resource_instance_ip_test.go
- scaleway/resource_instance_server.go
- scaleway/resource_instance_server_test.go
- scaleway/testdata/instance-ip-routed-downgrade.cassette.yaml
- scaleway/testdata/instance-ip-routed-ipv6.cassette.yaml
- scaleway/testdata/instance-ip-routed-migrate.cassette.yaml
- scaleway/testdata/instance-server-ip-removed.cassette.yaml
- scaleway/testdata/instance-server-ips-removed.cassette.yaml
- scaleway/testdata/instance-server-ips.cassette.yaml
- scaleway/testdata/instance-server-routed-ip-enable-with-ip.cassette.yaml
- scaleway/testdata/instance-server-routed-ip-enable.cassette.yaml
> feat(instance): support ip mobility

- scaleway/resource_k8s_cluster.go
Since fully public clusters (with no private network attached) are deprecated, we want to add a warning message to encourage these clusters' users to migrate before the end of service (Q1 2024)
> feat(k8s): add warning message for clusters with no PN

- scaleway/resource_rdb_read_replica.go
- scaleway/resource_rdb_read_replica_test.go
- scaleway/testdata/rdb-read-replica-basic.cassette.yaml
- scaleway/testdata/rdb-read-replica-different-zone.cassette.yaml
- scaleway/testdata/rdb-read-replica-multiple-endpoints.cassette.yaml
- scaleway/testdata/rdb-read-replica-private-network.cassette.yaml
- scaleway/testdata/rdb-read-replica-update.cassette.yaml
> feat(rdb): allow read replicas in a different zone

- docs/resources/instance_server.md
- scaleway/helpers_instance.go
- scaleway/resource_instance_server.go
- scaleway/resource_instance_server_test.go
- scaleway/testdata/instance-server-ip-migrate.cassette.yaml
I still haven't figured a way to give information about this behavior during plan.
It currently makes no difference and it shows that the ip may be detached as before
> feat(instance): do not detach ip when changing from ip_id to ip_ids

- docs/index.md
> docs: fix example snippet for storing state in scw object storage

- scaleway/helpers_object.go
- scaleway/resource_object_bucket.go
- scaleway/resource_object_bucket_test.go
- scaleway/testdata/object-bucket-basic.cassette.yaml
> feat(object): add api_endpoint field

- scaleway/resource_mnq_sqs_test.go
- scaleway/testdata/data-source-mnqsqs-basic.cassette.yaml
- scaleway/testdata/mnqsqs-already-activated.cassette.yaml
- scaleway/testdata/mnqsqs-basic.cassette.yaml
- scaleway/testdata/mnqsqs-credentials-basic.cassette.yaml
- scaleway/testdata/mnqsqs-queue-basic.cassette.yaml
- scaleway/testdata/mnqsqs-queue-default-project.cassette.yaml
API response changed to 404 from 403
> tests(mnq_sqs): change expected error to 404

- scaleway/resource_instance_server.go
> fix(instance_server): change from private image failed with marketplace

- docs/resources/documentdb_database.md
> doc(ddb): fix wrong url

- docs/resources/rdb_instance.md
- scaleway/helpers_rdb.go
- scaleway/resource_rdb_instance.go
- scaleway/resource_rdb_instance_test.go
- scaleway/testdata/data-source-rdb-acl-basic.cassette.yaml
- scaleway/testdata/data-source-rdb-database-backup-basic.cassette.yaml
- scaleway/testdata/data-source-rdb-database-basic.cassette.yaml
- scaleway/testdata/data-source-rdb-instance-basic.cassette.yaml
- scaleway/testdata/data-source-rdb-privilege-basic.cassette.yaml
- scaleway/testdata/rdb-acl-basic.cassette.yaml
- scaleway/testdata/rdb-database-backup-basic.cassette.yaml
- scaleway/testdata/rdb-database-basic.cassette.yaml
- scaleway/testdata/rdb-database-manual-delete.cassette.yaml
- scaleway/testdata/rdb-instance-backup-schedule.cassette.yaml
- scaleway/testdata/rdb-instance-capitalize.cassette.yaml
- scaleway/testdata/rdb-instance-disable-public-endpoint.cassette.yaml
- scaleway/testdata/rdb-instance-init-settings.cassette.yaml
- scaleway/testdata/rdb-instance-private-network-dhcp.cassette.yaml
- scaleway/testdata/rdb-instance-private-network-update.cassette.yaml
- scaleway/testdata/rdb-instance-private-network.cassette.yaml
- scaleway/testdata/rdb-instance-settings.cassette.yaml
- scaleway/testdata/rdb-instance-volume.cassette.yaml
- scaleway/testdata/rdb-instance-with-cluster.cassette.yaml
- scaleway/testdata/rdb-privilege-basic.cassette.yaml
- scaleway/testdata/rdb-read-replica-basic.cassette.yaml
- scaleway/testdata/rdb-read-replica-different-zone.cassette.yaml
- scaleway/testdata/rdb-read-replica-multiple-endpoints.cassette.yaml
- scaleway/testdata/rdb-read-replica-private-network.cassette.yaml
- scaleway/testdata/rdb-read-replica-update.cassette.yaml
- scaleway/testdata/rdb-user-basic.cassette.yaml
> feat(rdb): add possibility to remove public endpoint

- scaleway/resource_k8s_pool.go
- scaleway/testdata/data-source-k8s-cluster-basic.cassette.yaml
- scaleway/testdata/k8s-cluster-auto-upgrade.cassette.yaml
- scaleway/testdata/k8s-cluster-autoscaling.cassette.yaml
- scaleway/testdata/k8s-cluster-basic.cassette.yaml
- scaleway/testdata/k8s-cluster-multicloud.cassette.yaml
- scaleway/testdata/k8s-cluster-oidc.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-basic.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-kubelet-args.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-placement-group.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-public-ip-disabled.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-size.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-upgrade-policy.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-wait.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-zone.cassette.yaml
- scaleway/testdata/k8s-cluster-private-network.cassette.yaml
- scaleway/testdata/k8s-cluster-type-change.cassette.yaml
> fix(k8s): pool: read empty values in import generation

- docs/resources/object_bucket_policy.md
> docs(object): bucket policy: update examples

- scaleway/resource_rdb_instance.go
- scaleway/testdata/data-source-rdb-acl-basic.cassette.yaml
- scaleway/testdata/data-source-rdb-database-backup-basic.cassette.yaml
- scaleway/testdata/data-source-rdb-database-basic.cassette.yaml
- scaleway/testdata/data-source-rdb-instance-basic.cassette.yaml
- scaleway/testdata/data-source-rdb-privilege-basic.cassette.yaml
- scaleway/testdata/rdb-acl-basic.cassette.yaml
- scaleway/testdata/rdb-database-backup-basic.cassette.yaml
- scaleway/testdata/rdb-database-basic.cassette.yaml
- scaleway/testdata/rdb-privilege-basic.cassette.yaml
- scaleway/testdata/rdb-user-basic.cassette.yaml
> fix(rdb): fill empty values in import generation

- scaleway/resource_rdb_database.go
- scaleway/testdata/data-source-rdb-database-backup-basic.cassette.yaml
- scaleway/testdata/data-source-rdb-database-basic.cassette.yaml
- scaleway/testdata/rdb-database-backup-basic.cassette.yaml
- scaleway/testdata/rdb-database-basic.cassette.yaml
- scaleway/testdata/rdb-database-manual-delete.cassette.yaml
> fix(rdb): database: fill empty values in import generation

- scaleway/data_source_rdb_acl_test.go
- scaleway/resource_rdb_acl.go
- scaleway/testdata/data-source-rdb-acl-basic.cassette.yaml
- scaleway/testdata/rdb-acl-basic.cassette.yaml
> fix(rdb): acl: fill empty values in import generation

- docs/resources/rdb_read_replica.md
- scaleway/resource_rdb_read_replica_test.go
- scaleway/testdata/rdb-read-replica-different-zone.cassette.yaml
> fix(rdb): read replica: fix default value in doc

- docs/resources/k8s_cluster.md
- scaleway/resource_k8s_cluster.go
> doc(k8s): delete_additional_resources deletes empty private networks

- docs/data-sources/instance_placement_group.md
- scaleway/data_source_instance_placement_group.go
- scaleway/data_source_instance_placement_group_test.go
- scaleway/provider.go
- scaleway/testdata/data-source-instance-placement-group-basic.cassette.yaml
> feat(instance_placement_group): add datasource

- docs/resources/account_project.md
> docs(account_project): add example with provider configuration

- docs/resources/mnq_sqs_queue.md
Close #2296 
import is currently broken as it require different api keys as our mnq product does not use IAM
> docs(mnq_sqs_queue): remove import

- scaleway/data_source_vpc_private_network.go
I'm struggling adding tests because I don't understand how to setup the tests with the mocks
> feat: add the ability to filter pn per vpc_id

- docs/resources/function_cron.md
- scaleway/resource_function_cron.go
- scaleway/resource_function_cron_test.go
- scaleway/testdata/function-cron-basic.cassette.yaml
- scaleway/testdata/function-cron-name-update.cassette.yaml
- scaleway/testdata/function-cron-with-args.cassette.yaml
> feat(function_cron): add name attribute

- docs/resources/function.md
- docs/resources/function_cron.md
- scaleway/resource_function.go
- scaleway/resource_function_cron.go
- scaleway/resource_function_test.go
> fix(function): fix missing fields in read

- scaleway/helpers.go
> fix: expandStringsPtr

- docs/resources/k8s_cluster.md
Reverts scaleway/terraform-provider-scaleway#2375
> Revert "doc(k8s): kubeconfig: add IAM authentication method"

- scaleway/resource_object_bucket.go
- scaleway/resource_object_bucket_policy.go
> fix(object): read `project_id` only when authorized

- docs/resources/rdb_privilege.md
Update scaleway_rdb_privilege documentation and add coherence to the example.
> docs(rdb_privilege): improve example

- docs/resources/redis_cluster.md
- scaleway/resource_redis_cluster.go
- scaleway/resource_redis_cluster_test.go
- scaleway/testdata/redis-cluster-migrate-cluster-size-with-ipam-endpoint.cassette.yaml
- scaleway/testdata/redis-cluster-migrate-cluster-size-with-static-endpoint.cassette.yaml
> fix(redis): migrate cluster size

- docs/resources/tem_domain.md
- scaleway/resource_tem_domain.go
> feat(tem) : add ressource SMTPS auth user and most exemples in doc

- docs/data-sources/instance_security_group.md
- docs/resources/instance_security_group.md
- docs/resources/instance_security_group_rules.md
Update the port_range usage and remove the outdated CIDR mention.
> fix(instance): update security rule port_range usage

- docs/resources/rdb_instance.md
It's looks like it's possible and it works fine through the web UI or using terraform
> Fix docs saying it's not possible to downgrade RDB node type

- go.mod
- go.sum
- internal/services/k8s/cluster.go
This allows authorized users to create a cluster with no CNI.
Closes #2523
> feat(k8s): allow cluster creation with `cni=none`

- docs/resources/tem_domain.md
- internal/services/tem/domain.go
- internal/services/tem/domain_test.go
- internal/services/tem/testdata/domain-basic.cassette.yaml
> feat(tem): add dmarc name and config in ressource

- internal/services/rdb/instance_test.go
- internal/services/rdb/testdata/instance-change-node-type.cassette.yaml
> test(rdb): add test for instance update node type

- docs/resources/apple_silicon.md
- docs/resources/baremetal_server.md
- docs/resources/instance_image.md
- docs/resources/instance_ip.md
- docs/resources/instance_ip_reverse_dns.md
- docs/resources/instance_placement_group.md
- docs/resources/instance_private_nic.md
- docs/resources/instance_security_group.md
- docs/resources/instance_security_group_rules.md
- docs/resources/instance_server.md
- docs/resources/instance_snapshot.md
- docs/resources/instance_user_data.md
- docs/resources/instance_volume.md
- docs/resources/k8s_cluster.md
- docs/resources/k8s_pool.md
Fixed outdated link to API documentation for:
* Apple Silicon
* Elastic Metal
* Instances
* Kubernetes
* Webhosting
> chore(all): fixed boken links

- docs/resources/documentdb_private_network_endpoint.md
- internal/services/documentdb/private_network_endpoint.go
- internal/services/documentdb/private_network_endpoint_test.go
close [#2588](https://github.com/scaleway/terraform-provider-scaleway/issues/2588)
> fix(documentdb): fix private network support

- docs/data-sources/ipam_ip.md
- docs/data-sources/mnq_sqs.md
- docs/data-sources/vpc_gateway_network.md
- docs/data-sources/vpc_public_gateway_ip.md
PR to fix small typos missed out of previous PRs (Messaging & Queing, VPC, IPAM)
> fix(docs): fix straggling docs

- docs/data-sources/lb.md
- docs/data-sources/lb_acls.md
- docs/data-sources/lb_backend.md
- docs/data-sources/lb_backends.md
- docs/data-sources/lb_certificate.md
- docs/data-sources/lb_frontend.md
- docs/data-sources/lb_frontends.md
- docs/data-sources/lb_ip.md
- docs/data-sources/lb_ips.md
- docs/data-sources/lb_route.md
- docs/data-sources/lb_routes.md
- docs/data-sources/lbs.md
- docs/resources/lb.md
- docs/resources/lb_acl.md
- docs/resources/lb_backend.md
- docs/resources/lb_certificate.md
- docs/resources/lb_frontend.md
- docs/resources/lb_ip.md
- docs/resources/lb_route.md
Reviewed LB doc for links, grammar, typos, capitalization in accordance with guidelines etc.
> docs(lb): review lb doc

- internal/services/tem/domain_validation_test.go
- internal/services/tem/testdata/domain-validation-validation.cassette.yaml
> tests(tem): add dmarc in test validation

- .github/labeler.yml
- .github/workflows/labeler.yml
https://github.com/actions/labeler
> chore: add support for labeler

- internal/services/secret/version_data_source.go
> fix(secret_version): return error when secret name is invalid

- internal/services/rdb/instance.go
fix [#2711](https://github.com/scaleway/terraform-provider-scaleway/issues/2711)
> fix(rbd): fix diff case for engine

- internal/services/tem/domain_test.go
- internal/services/tem/testdata/domain-basic.cassette.yaml
> fix(tem): add sub domain in DMARC in test

- docs/resources/cockpit_alert_manager.md
> docs(cockpit): update contact_points in alert_manager

- internal/services/iot/network.go
> fix(iot): add region to network

- internal/services/lb/data_source_lb_ip.go
- internal/services/lb/data_source_lb_ip_test.go
- internal/services/lb/testdata/data-source-ip-basic.cassette.yaml
> fix(scaleway_lb_ip): add support to precise the zone in which the ip was reserved

- internal/services/instance/server.go
> fix(instance_server): ignore diff for user_data.ssh-host-fingerprints

- docs/resources/tem_domain.md
close [#2883](https://github.com/scaleway/terraform-provider-scaleway/issues/2883)
> docs(tem): specify fr-par region requirement

- docs/resources/webhosting.md
fixed broken link to web hosting api documentation
> docs(webhosting): fix link to api documentation

- docs/resources/container.md
> docs(container): fix healthcheck example

- internal/services/block/helpers_block.go
- internal/services/block/testdata/volume-update-size.cassette.yaml
- internal/services/block/volume.go
- internal/services/block/volume_test.go
> fix(block): trigger ForceNew only when size_in_gb is reduced

- internal/verify/uuid.go
> fix(baremetal): suppress misleading warning when using offer data source

- docs/resources/block_snapshot.md
- internal/services/block/snapshot.go
- internal/services/block/snapshot_test.go
- internal/services/block/testdata/snapshot-to-s3.cassette.yaml
- internal/services/object/object_test.go
- internal/services/object/testfuncs/checks.go
> feat(block): support export to s3

- docs/guides/increase-resources-timeout.md
- docs/resources/k8s_cluster.md
- docs/resources/k8s_pool.md
> doc: guide how to increase timeout resources

- internal/services/rdb/acl.go
- internal/services/rdb/testdata/acl-basic.cassette.yaml
- internal/services/rdb/testdata/data-source-acl-basic.cassette.yaml
close [#3206](https://github.com/scaleway/terraform-provider-scaleway/issues/3206)
> fix(rdb): add pagination support for ACL rules

- internal/services/domain/record.go
- internal/services/domain/record_test.go
- internal/services/domain/testdata/domain-record-basic.cassette.yaml
> fix(domain): correct zone deletion behavior to keep empty zones by default

- internal/services/rdb/instance.go
- internal/services/rdb/instance_test.go
- internal/services/rdb/testdata/acl-pagination.cassette.yaml
- internal/services/rdb/testdata/instance-from-snapshot-with-private-network.cassette.yaml
> fix(rdb): enable private_network when restoring from snapshot
