scaleway/terraform-provider-scaleway

- scaleway/resource_scaleway_ip_test.go
- scaleway/resource_scaleway_security_group_test.go
- scaleway/resource_scaleway_server_test.go
- scaleway/resource_scaleway_volume_attachment.go
- scaleway/resource_scaleway_volume_test.go
- scaleway/scaleway_sweeper_test.go
\cc @stack72. thanks for pointing me at the AWS provider, man!
```
go test . -v -sweep=par1
2017/06/19 19:18:55 [DEBUG] Running Sweepers for region (par1):
2017/06/19 19:18:55 [DEBUG] Destroying the volumes in (par1)
2017/06/19 19:18:55 [DEBUG] HEAD /volumes
2017/06/19 19:18:55 [DEBUG] [[HEAD https://cp-par1.scaleway.com/volumes?]]: %!v(MISSING)
2017/06/19 19:18:55 [DEBUG] GET /volumes
2017/06/19 19:18:55 [DEBUG] [[GET https://cp-par1.scaleway.com/volumes]]: %!v(MISSING)
2017/06/19 19:18:55 [DEBUG] [Response]: [[200 {"volumes": []}]]
%!v(MISSING)
2017/06/19 19:18:55 [DEBUG] Destroying the ips in (par1)
2017/06/19 19:18:55 [DEBUG] HEAD /ips
2017/06/19 19:18:55 [DEBUG] [[HEAD https://cp-par1.scaleway.com/ips?]]: %!v(MISSING)
2017/06/19 19:18:55 [DEBUG] GET /ips
2017/06/19 19:18:55 [DEBUG] …
```
> chore(provider) basic sweeper implementation

- scaleway/helpers.go
closes #4 - when Scaleway returns invalid JSON the terraform provider crashed bc/ the assumption was that a server is always returned - which in this case isn't.
> fix(crash): handle scaleway crashing bc of invalid JSON

- scaleway/provider.go
- scaleway/resource_volume_attachment.go
4a153c47beda7abd8b061aebca1e295974f975cc introduced a deadlock caused my
duplicated calls to `mu.Lock()` in a function as well as inside a
`resource.Retry` closure.
fixes #3
```
--- PASS: TestAccScalewayVolumeAttachment_Basic (452.97s)
PASS
```
> fix(volume_attachment): fix volume_attachment deletion

- scaleway/resource_server.go
this changeset ensures that if the IP attachment fails due to an invalid input, the creation `server` resource fails.
previously this was silently ignored, which led to #1.
```bash
make testacc TESTARGS="-run='TestAccScalewayServer'"
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run='TestAccScalewayServer' -timeout 120m
?       github.com/terraform-providers/terraform-provider-scaleway    [no test files]
=== RUN   TestAccScalewayServer_importBasic
--- PASS: TestAccScalewayServer_importBasic (101.07s)
=== RUN   TestAccScalewayServer_Basic
--- PASS: TestAccScalewayServer_Basic (118.88s)
=== RUN   TestAccScalewayServer_ExistingIP
--- PASS: TestAccScalewayServer_ExistingIP (102.68s)
=== RUN   TestAccScalewayServer_Volumes …
```
> resource server: improve IP attachment usability

- vendor/github.com/nicolai86/scaleway-sdk/api/api.go
- vendor/github.com/nicolai86/scaleway-sdk/api/availability.go
- vendor/github.com/nicolai86/scaleway-sdk/api/volume.go
- vendor/vendor.json
prerequisite to implement https://github.com/terraform-providers/terraform-provider-scaleway/issues/17
> update scaleway-api SDK

- scaleway/data_source_bootscript.go
Given a bootscript datasource without proper filter, the existing data source would crash as the `isMatch` variable is not set. See #21 for an example of this.
This PR initializes `isMatch` to a function to ensure this doesn't happen anymore.
> fix crash with invalid bootscript filter

- scaleway/helpers.go
- scaleway/resource_server.go
- scaleway/resource_server_test.go
- scaleway/resource_volume.go
Add support for `volume` with `size_in_gb` of `0` in the `scaleway_server` resource - resolves #19 .
Now, the following terraform code is valid:
```
resource "scaleway_server" "base" {
name = "test"
image = "some-guid"
type = "VC1S"
volume {
size_in_gb = 0
type = "l_ssd"
}
}
```
previously, this would have errored because the volume size of 0 was disallowed. Now this is valid and it allows for the creation of terraform modules which span all available scaleway instance types.
The tests remain green, as this is only a small behaviour adjustment:
```
make testacc TESTARGS="-run='TestAccScalewayServer'"
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run='TestAccScalewayServer' -timeout 120m
? …
```
> add zero sized volumes to scaleway_server

- scaleway/config.go
- scaleway/helpers.go
- scaleway/resource_server.go
fetch the list of known server types on initialization and cache it to validate r/server types later.
closes #17
all server-related tests remain green with this change:
```
make testacc TESTARGS="-run='TestAccScalewayServer_'"
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run='TestAccScalewayServer_' -timeout 120m
=== RUN   TestAccScalewayServer_importBasic
--- PASS: TestAccScalewayServer_importBasic (91.70s)
=== RUN   TestAccScalewayServer_Basic
--- PASS: TestAccScalewayServer_Basic (96.95s)
=== RUN   TestAccScalewayServer_ExistingIP
--- PASS: TestAccScalewayServer_ExistingIP (88.13s)
=== RUN   TestAccScalewayServer_Volumes
--- PASS: …
```
> best effort commercial server type validation

- scaleway/resource_security_group_rule.go
- scaleway/resource_security_group_rule_test.go
- vendor/github.com/nicolai86/scaleway-sdk/api/security_group_rule.go
- vendor/vendor.json
The Scaleway API returns the created Security Group, but the SDK did not surface that information.
I've fixed this in my fork of the SDK and improved the terraform provider to handle this situation better.
closes #25
> improve scaleway SDK to return created SG rule

- vendor/github.com/nicolai86/scaleway-sdk/api.go
- vendor/github.com/nicolai86/scaleway-sdk/user_data.go
- vendor/vendor.json
the SDK update allows custom HTTPClient implementations so we can implement
rate limited retry without touching all resources/ datasources.
related #30
> update scaleway-sdk dependency

- scaleway/helpers.go
- scaleway/resource_server.go
- scaleway/resource_volume_attachment.go
Explicitly declare valid pending states for startup/ shutdown. 
This will allow the proper detection of hung servers as `stopped` is no valid pending state for `startup`
closes #31
> detect hung servers by improving startup/ shutdown detection

- scaleway/resource_security_group.go
- scaleway/resource_security_group_rule.go
- vendor/github.com/nicolai86/scaleway-sdk/security_group.go
- vendor/github.com/nicolai86/scaleway-sdk/security_group_rule.go
- vendor/vendor.json
- website/docs/r/security_group.html.markdown
As specified in #33, it is possible to control the security group default rule creation.
This CR exposes a new attribute, `enable_default_security` which can be set to `false` to disable the default security group rules applied by scaleway. Default: `true`.
closes #33
> Allow security group default rules to be disabled

- scaleway/resource_server.go
See #42. The follow terraform code produces a crash:
```
provider "scaleway" {}
data "scaleway_image" "centos_7_3" {
architecture = "x86_64"
name         = "CentOS 7.3"
}
resource "scaleway_server" "test" {
name        = "test"
image       = "${data.scaleway_image.centos_7_3.id}"
type        = "VC1M"
tags        = ["test"]
enable_ipv6 = true
state       = "stopped"
volume {
size_in_gb = 50
type       = "l_ssd"
}
}
```
breaks if the server is in a stopped state, in which case the IPv6 information is not available.
fixes #42
> guard against missing ipv6 information

- scaleway/resource_ip.go
- scaleway/resource_ip_test.go
- vendor/github.com/nicolai86/scaleway-sdk/ip.go
- vendor/vendor.json
- website/docs/r/ip.html.markdown
This PR adds support to manage `scaleway_ip`s `reverse` attribute.
The change includes an update to the `github.com/nicolai86/scaleway-sdk` dependency, as well as document and test updates.
The changed resource looks like this:
```
resource "scaleway_ip" "test" {
reverse = "www.google.com"
}
```
Once merged, closes #34
> add support for managing ip reverse attribute

- scaleway/config.go
when using the provider over a slow uplink like an airplane or train
sometimes no response is provided. these cases should be handled as a
retry.
instead, the provider crashes at the moment
> guard against crashes due to missing responses

- website/docs/index.html.markdown
Unfortunaly 20GB disk sizes ae not supported at Scaleway.
> Fix disk size

- scaleway/helpers.go
- scaleway/resource_server.go
- scaleway/resource_volume.go
- scaleway/resource_volume_attachment.go
- vendor/github.com/nicolai86/scaleway-sdk/server.go
- vendor/github.com/nicolai86/scaleway-sdk/tasks.go
- vendor/github.com/nicolai86/scaleway-sdk/volume.go
- vendor/vendor.json
the sdk has been updated to return the result of the operations.
moving forward this will allow us to reduce the number of API calls
made, as well as verify the results of operations better.
once the tests are green I'll merge this optimistically.
> update sdk dependency

- scaleway/resource_ip.go
- scaleway/resource_ip_test.go
- scaleway/resource_security_group.go
- scaleway/resource_security_group_rule.go
- scaleway/resource_security_group_rule_test.go
- scaleway/resource_security_group_test.go
- scaleway/resource_server.go
- scaleway/resource_server_test.go
- scaleway/resource_volume.go
- vendor/github.com/nicolai86/scaleway-sdk/container.go
- vendor/github.com/nicolai86/scaleway-sdk/image.go
- vendor/github.com/nicolai86/scaleway-sdk/ip.go
- vendor/github.com/nicolai86/scaleway-sdk/organization.go
- vendor/github.com/nicolai86/scaleway-sdk/permissions.go
- vendor/github.com/nicolai86/scaleway-sdk/quota.go
- vendor/github.com/nicolai86/scaleway-sdk/security_group.go
- vendor/github.com/nicolai86/scaleway-sdk/security_group_rule.go
- vendor/github.com/nicolai86/scaleway-sdk/server.go
- vendor/github.com/nicolai86/scaleway-sdk/snapshot.go
- vendor/github.com/nicolai86/scaleway-sdk/tasks.go
- vendor/github.com/nicolai86/scaleway-sdk/user.go
- vendor/github.com/nicolai86/scaleway-sdk/volume.go
- vendor/vendor.json
again maintainability update.
once the tests are green I'll merge this optimistically.
> update the dependecy for scaleway sdk

- scaleway/helpers.go
- scaleway/resource_server.go
- scaleway/resource_volume_attachment.go
Scaleway has a task api, which can be used when polling for server actions.
e.g., when you want a server to start, scaleway posts an action to the server (`/servers/:server-id/actions`) which returns a task object. The server change is executed once the task is marked as completed, which can be verified by polling `/tasks/:task-id`. 
This should allow us to better detect errors, e.g. if a server can not be started the task won't enter the `success` state.
> replace waiting on server results with task api

- scaleway/import_token_test.go
- scaleway/provider.go
- scaleway/resource_token.go
- scaleway/resource_token_test.go
- vendor/github.com/nicolai86/scaleway-sdk/tokens.go
- vendor/github.com/nicolai86/scaleway-sdk/user.go
- vendor/vendor.json
- website/docs/r/token.html.markdown
- website/scaleway.erb
this PR adds a new scaleway resource: `scaleway_token`.
`scaleway_token` can be used to generate additional scaleway access tokens; usage looks like this:
```
resource "scaleway_token" "karls_token" {
expires = false
description = "karls scaleway access: karl@company.com"
}
```
See the attached documentation for details. Tests are green:
```
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run='TestAccScalewayToken_Basic' -timeout 120m
=== RUN   TestAccScalewayToken_Basic
--- PASS: TestAccScalewayToken_Basic (19.19s)
PASS
ok  	github.com/terraform-providers/terraform-provider-scaleway/scaleway	19.215s
```
> add scaleway_token resource

- scaleway/import_user_data_test.go
- scaleway/provider.go
- scaleway/resource_server.go
- scaleway/resource_server_test.go
- scaleway/resource_user_data.go
- scaleway/resource_user_data_test.go
- website/docs/r/server.html.markdown
- website/docs/r/user_data.html.markdown
- website/scaleway.erb
this PR adds a `scaleway_user_data` resource to manage server specific user data.
Example usage:
```
resource "scaleway_server" "base" {
name = "test"
image = "5faef9cd-ea9b-4a63-9171-9e26bec03dbc"
type = "C1"
state = "stopped"
user_data {
key = "gcp_password"
value = "supersupersecret"
}
}
resource "scaleway_user_data" "gcp" {
server = "${scaleway_server.base.id}"
key = "gcp_username"
value = "supersecret"
}
```
In this example two user data objects are being created: one, inline in the `scaleway_server` resource, and one as a separate resource.
Both user data objects can be accessed from the server. For more details see the [user data](https://developer.scaleway.com/#user-data) documentation from scaleway.
test are green:
```
n='TestAccScalewayUserData_Basic'"
==> Checking that code …
```
> add scaleway_user_data resource

- scaleway/resource_server.go
- scaleway/resource_server_test.go
- vendor/github.com/hashicorp/terraform/helper/structure/expand_json.go
- vendor/github.com/hashicorp/terraform/helper/structure/flatten_json.go
- vendor/github.com/hashicorp/terraform/helper/structure/normalize_json.go
- vendor/github.com/hashicorp/terraform/helper/structure/suppress_json_diff.go
- vendor/github.com/hashicorp/terraform/helper/validation/validation.go
- vendor/github.com/nicolai86/scaleway-sdk/server.go
- vendor/vendor.json
- website/docs/r/server.html.markdown
this PR adds support for the [newly introduced boot_type](https://blog.online.net/2018/04/19/scaleway-feature-improvements-custom-kernel-security-group-live-reload-imagehub-packer/) attribute for scaleway server resources:
```
resource "scaleway_server" "base" {
name = "test"
image = "e20532c4-1fa0-4c97-992f-436b8d372c07"
type = "VC1S"
tags = [ "terraform-test" ]
boot_type = "local"
}
```
valid values are `local` and `bootscript` for x86_64, as well as `bootscript` for arm instance types.
Tests are green:
```
=== RUN   TestAccScalewayDataSourceBootscript_Filtered
--- PASS: TestAccScalewayDataSourceBootscript_Filtered (8.64s)
=== RUN   TestAccScalewayDataSourceImage_Basic
--- PASS: TestAccScalewayDataSourceImage_Basic (26.29s)
=== RUN   TestAccScalewayDataSourceImage_Filtered
--- PASS: …
```
> resource/server: support boot_type

- scaleway/config.go
- vendor/github.com/nicolai86/scaleway-sdk/api.go
- vendor/github.com/nicolai86/scaleway-sdk/availability.go
- vendor/vendor.json
fixes #62 by switching to a different Scaleway API to fetch server availability.
Also, it allows the validation to be disabled by setting `DISABLE_SCALEWAY_SERVER_TYPE_VALIDATION`
> switch server type API

- scaleway/resource_server.go
- vendor/github.com/nicolai86/scaleway-sdk/availability.go
- vendor/vendor.json
Before creating a new `scaleway_server` instance, the availability is detected using the compute api specific `/products/servers/availability` API. 
Valid return values are (`available`, `scarce`, `shortage`), where `shortage` identifies out of stock.
In this case the provide will fail to create a new instance.
closes https://github.com/terraform-providers/terraform-provider-scaleway/issues/66 .
> r/server: validate instance type availability

- scaleway/resource_server.go
instead of blocking for the entire resource creation duration, only
block for the actual call to create/ update the scaleway_server
resource; do not block while polling for the resource state.
this should speed up creating multiple servers considerably.
according to @sieben this should be safe now.
closes #65
> support concurrent server creation

- CHANGELOG.md
- scaleway/helpers.go
- scaleway/resource_ip_test.go
- scaleway/resource_server.go
- scaleway/resource_server_test.go
- scaleway/resource_user_data_test.go
- scaleway/resource_volume_attachment.go
- scaleway/resource_volume_attachment_test.go
#72 introduced a race condition when `volume_attachments` are used together with `server` resources, as the server might currently be starting/ stopping.
This PR introduces per-server wait groups to synchronise the different actions: all server stop/ start actions are now managed by `startServer` and `stopServer`, and these actions ensure that no server is concurrently being started/ stopped.
@meyskens would be great if you could verify that this fixes your issue.
Multiple test runs shows all tests are green:
```
make testacc
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 120m
?     github.com/terraform-providers/terraform-provider-scaleway  [no test files]
=== RUN   TestAccScalewayDataSourceBootscript_Filtered …
```
> fix race-condition between server & volume_attachment

- website/docs/d/bootscript.html.markdown
- website/docs/d/image.html.markdown
- website/docs/r/ip.html.markdown
- website/docs/r/security_group.html.markdown
- website/docs/r/security_group_rule.html.markdown
- website/docs/r/server.html.markdown
- website/docs/r/ssh_key.html.markdown
- website/docs/r/token.html.markdown
- website/docs/r/user_data.html.markdown
- website/docs/r/volume.html.markdown
- website/docs/r/volume_attachment.html.markdown
This PR fixes a couple of minor issues I noticed whilst scrolling through the docs:
- converts the `warning` boxes to yellow boxes to make them more prominent (you can use `->` for a blue info box / `~>` for a yellow info box)
- removes the backslashes from the resource names since they're not needed
- fixes the `attribute reference` title (the markdown parser needs a blank line either side)
> Documentation edits

- scaleway/data_source_volume.go
- scaleway/data_source_volume_test.go
- scaleway/provider.go
- vendor/github.com/hashicorp/terraform/helper/acctest/acctest.go
- vendor/github.com/hashicorp/terraform/helper/acctest/random.go
- vendor/github.com/hashicorp/terraform/helper/acctest/remotetests.go
- vendor/vendor.json
- website/docs/d/volume.html.markdown
- website/docs/r/volume.html.markdown
- website/scaleway.erb
Used for querying an existing Scaleway volume by it's name:
```
data "scaleway_volume" "test" {
name = "some-data"
}
```
> New Data Source: `scaleway_volume`

- website/docs/r/security_group.html.markdown
- website/docs/r/security_group_rule.html.markdown
- website/docs/r/user_data.html.markdown
- website/docs/r/volume.html.markdown
- website/docs/r/volume_attachment.html.markdown
- website/scaleway.erb
Noticed the sidebar didn't highlight correctly for the Security Groups / Volume attachment resources
This PR also adds the SSH Key Resource to the sidebar, since it's currently missing
> Docs: fixing the sidebar highlight

- scaleway/data_source_security_group.go
- scaleway/data_source_security_group_test.go
- scaleway/provider.go
- scaleway/resource_security_group_test.go
- website/docs/d/security_group.html.markdown
- website/scaleway.erb
Allows retrieving information about a given Security Group. Usage:
```hcl
data "scaleway_security_group" "test" {
name = "my-security-group"
}
```
```
$ acctests scaleway TestAccScalewaySecurityGroupDataSource_Basic
=== RUN   TestAccScalewaySecurityGroupDataSource_Basic
[DEBUG] GET https://cp-par1.scaleway.com//products/servers/availability
[DEBUG] POST https://cp-par1.scaleway.com/security_groups
[DEBUG] HEAD https://cp-par1.scaleway.com/security_groups/4cb41897-530c-457f-8419-007dedfe268d?
[DEBUG] GET https://cp-par1.scaleway.com/security_groups/4cb41897-530c-457f-8419-007dedfe268d
[DEBUG] HEAD https://cp-par1.scaleway.com/security_groups?
[DEBUG] GET https://cp-par1.scaleway.com/security_groups
[DEBUG] HEAD https://cp-par1.scaleway.com/security_groups/4cb41897-530c-457f-8419-007dedfe268 …
```
> New Data Source: `scaleway_security_group`

- scaleway/data_source_image.go
- scaleway/data_source_image_test.go
- website/docs/d/image.html.markdown
once merged fixes #81.
Now the data source for images supports `most_recent` to only return the most recent image if multiple matches exist:
```
provider "scaleway" {
region       = "ams1"
}
data "scaleway_image" "ubuntu" {
architecture = "x86_64"
name         = "Ubuntu Xenial"
most_recent  = true
}
output "image_id" {
value = "${data.scaleway_image.ubuntu.id}" # will be ca9a9340-92e8-4c5f-8ae1-423466f7ef30 for AMS1
}
```
> d/image: add most_recent filter to support multiple matches

- scaleway/resource_token.go
- scaleway/resource_token_test.go
- vendor/github.com/nicolai86/scaleway-sdk/tokens.go
- vendor/vendor.json
- website/docs/r/token.html.markdown
Scaleway recently overhauled their token API - now there are a couple of changes:
- there are two new attributes: `access_key` and `secret_key`.
- the `ID` is no longer present in the response payload. It seems it has been deprecated in favor of `access_key`
- Fetching keys can be done by the AccessKey instead of the ID, too.
To make this a non-breaking change the SDK now sets the ID when reading with a specific ID.
Note that due to the API changes on Scaleway's side the tests are broken without this change.
All tests are green (together with #87)
```
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 120m
=== RUN …
```
> fix token API not returning IDs anymore

- scaleway/helpers.go
- scaleway/resource_ip.go
- scaleway/resource_security_group.go
- scaleway/resource_security_group_rule.go
- scaleway/resource_server.go
- scaleway/resource_server_test.go
- scaleway/resource_ssh_key.go
- scaleway/resource_token.go
- scaleway/resource_user_data.go
- scaleway/resource_user_data_test.go
- scaleway/resource_volume.go
- scaleway/resource_volume_attachment.go
- scaleway/resource_volume_attachment_test.go
As reported in #83 recreation of servers due to image id changes does not work.
I've checked and it seems that the task API introduced in #55 stopped returning correct data - e.g. long after the server is shutdown the task is still in `pending` state.
So this change effectively reverts the change from #55 while also removing most of the mutexes placed around the provider.
There's also been a new testcase to ensure that there's no regression moving forward.
All tests are green (together with #86):
```
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 120m
=== RUN   TestAccScalewayDataSourceBootscript_Filtered
--- PASS: …
```
> fix server recreation with changed image_id

- scaleway/resource_token.go
the `secret_key` is not present in subsequent read operations, so we set
it after creation and fallback to the old semantics of using the ID if
it's not set.
we'll probably need to support a different way if important a token in
the future.
> fix token import/ subsequent read

- vendor/github.com/nicolai86/scaleway-sdk/api.go
- vendor/github.com/nicolai86/scaleway-sdk/container.go
- vendor/vendor.json
the updated SDK includes all methods to use the new bucket API, and also
includes naive rate limiting which should go hand-in-hand with the
removed mutex
> provider/scaleway: update SDK

- scaleway/provider.go
- scaleway/resource_bucket.go
- scaleway/resource_bucket_test.go
- website/docs/r/bucket.html.markdown
- website/scaleway.erb
This PR adds a new resource to the Scaleway provider: `scaleway_bucket`.
This can be merged once Scaleway objectstorage is out of GA.
```
make testacc TESTARGS="-run='TestAccScalewayBucket'"
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run='TestAccScalewayBucket' -timeout 120m
=== RUN   TestAccScalewayBucket
--- PASS: TestAccScalewayBucket (13.35s)
PASS
ok  	github.com/terraform-providers/terraform-provider-scaleway/scaleway
```
The PR includes docs, tests as well as the resource itself.
> provider/scaleway: add scaleway_bucket resource

- scaleway/resource_security_group.go
- scaleway/resource_security_group_test.go
- scaleway/resource_server.go
- scaleway/resource_server_test.go
- vendor/github.com/nicolai86/scaleway-sdk/security_group.go
- vendor/vendor.json
- website/docs/r/security_group.html.markdown
- website/docs/r/server.html.markdown
this was recently announced for servers and security groups.
security groups can be stateful, and support default inbound and
outbound policies now:
```
resource "scaleway_security_group" "base" {
name = "public"
description = "public gateway"
stateful = true 
inbound_default_policy = "accept"
outbound_default_policy = "drop"
}
```
for details, see the launch blog post:
https://www.scaleway.com/docs/how-to-activate-a-stateful-cloud-firewall/
also, servers now support for cloud-init using user-data.
```
resource "scaleway_server" "base" {
name = "test"
image = "%s"
type = "C1"
tags = [ "terraform-test" ]
cloudinit = <<EOF
#cloud-config
apt_update: true
apt_upgrade: true
EOF
}
```
for details, see the launch blog post:
https://blog.online.net/2018/07/05/introducing-scaleway-cloud-init-suppor …
> add stateful security gorups and cloudinit for servers

- scaleway/provider.go
- scaleway/resource_ip.go
- scaleway/resource_ip_reverse_dns.go
- scaleway/resource_ip_reverse_dns_test.go
- website/docs/r/ip.html.markdown
- website/docs/r/ip_reverse_dns.html.markdown
some usecases like dynamic reverse dns result in circular dependencies
between `scaleway_ip` and `scaleway_server` resources.
To break this cycle the `reverse` attribute on `scaleway_ip` is going to
be deprecated, and instead a new `scaleway_ip_reverse_dns` resource is
made available, which allows the IP to be created before the reverse DNS
is persisted.
Tests for the new resource as well as old modified resource are green.
Once merged this will fix use cases like https://github.com/terraform-providers/terraform-provider-scaleway/issues/88
> introduce new scaleway_ip_reverse_dns resource

- website/docs/index.html.markdown
These are just a few small changes in the docs to fix bullets so they render properly and a few formatting fixes.
Currently it shows the `+` instead of as a bulleted list.
> Fix bullets and formatting in docs

- scaleway/resource_ssh_key.go
Hello,
A small change to avoid using `trimspace()` Terraform function when adding keys generated by `ssh-keygen` and by Terraform TLS provider. Both generate keys with trailing newline character, which makes them to be rejected by Scaleway API. For details see https://community.scaleway.com/t/proposal-ssh-key-add-api-trim-spaces-on-server-side/7376
> Ignore leading and trailing whitespaces when adding public SSH key

- scaleway/provider.go
Hey, instead of returning the `SCALEWAY_ORGANIZATION` env value, the key is returned.
> Return the env org value instead of the key

- scaleway/provider.go
Similar to https://github.com/terraform-providers/terraform-provider-scaleway/pull/113 this fixes another bug introduced in https://github.com/terraform-providers/terraform-provider-scaleway/pull/111
Without this patch (and #113 ), the provider unfortunately can't authenticate against the API via ENV variables, which can also be seen by running any acceptance test:
```
=== RUN   TestAccScalewayBucket
--- FAIL: TestAccScalewayBucket (5.27s)
testing.go:538: Step 0 error: Error applying: 1 error(s) occurred:
* scaleway_bucket.base: 1 error(s) occurred:
* scaleway_bucket.base: StatusCode: 400, Type: invalid_request_error, APIMessage:  [31mValidation Error [0m, Details: map[organization:[SCALEWAY_ORGANIZATION is not a valid UUID.]]
FAIL
```
> provider: Source SCALEWAY_ORGANIZATION variable correctly

- go.mod
- scaleway/config.go
- vendor/modules.txt
This is to enable logging of all requests and responses which go through the SDK (in `>=DEBUG` mode) to make debugging easier. This also helped in #114
```
---[ REQUEST ]---------------------------------------
POST /containers HTTP/1.1
Host: sis-ams1.scaleway.com
User-Agent: scaleway-sdk
Content-Length: 65
Content-Type: application/json
X-Auth-Token: <redacted>
Accept-Encoding: gzip
{
"name": "terraform-test",
"organization": "SCALEWAY_ORGANIZATION"
}
-----------------------------------------------------
2019/03/22 20:42:22 [DEBUG] Scaleway API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 400 BAD REQUEST
Connection: close
Content-Length: 140
Content-Type: application/json
Date: Fri, 22 Mar 2019 20:42:22 GMT
Server: Tengine
{
"fields": {
"organization": …
```
> provider: Enable request/response logging

- scaleway/import_server_test.go
this changes if the server being imported is booting, so we can safely
ignore it§
> fix/scaleway_server: ignore state_detail in import

- scaleway/data_source_image_test.go
Fixes data source tests due to old images:
```
------- Stdout: -------
=== RUN   TestAccScalewayDataSourceImage_Basic
--- FAIL: TestAccScalewayDataSourceImage_Basic (7.97s)
testing.go:538: Step 0 error: Error refreshing: 1 error(s) occurred:
* data.scaleway_image.ubuntu: 1 error(s) occurred:
* data.scaleway_image.ubuntu: data.scaleway_image.ubuntu: The query returned no result. Please refine your query.
FAIL
```
> fix data src tests to more recent ubuntu

- scaleway/resource_token.go
- website/docs/r/token.html.markdown
Related to #143 
For security reasons, we estimate that users should not create tokens with terraform.
> doc: deprecate scaleway_token

- scaleway/resource_ssh_key.go
- website/docs/r/ssh_key.html.markdown
Related to #143
For security reasons, we estimate that users should not manage ssh keys with terraform.
> doc: deprecate scaleway_ssh_key

- scaleway/resource_bucket.go
- website/docs/r/bucket.html.markdown
Related to #143
This resource is deprecated and will be removed in the next major version.
Please use scaleway_storage_object_bucket instead.
> doc: deprecate scaleway_bucket

- scaleway/config.go
New SDK already has logging of request. So we shouldn't log request body in retryablehttpclient when using new SDK.
> fix: omit double logging with new SDK

- website/docs/d/bootscript.html.markdown
- website/docs/d/image.html.markdown
- website/docs/d/security_group.html.markdown
- website/docs/d/volume.html.markdown
- website/docs/index.html.markdown
- website/docs/r/bucket.html.markdown
- website/docs/r/compute_instance_ip.html.markdown
- website/docs/r/ip.html.markdown
- website/docs/r/ip_reverse_dns.html.markdown
- website/docs/r/security_group.html.markdown
- website/docs/r/security_group_rule.html.markdown
- website/docs/r/server.html.markdown
- website/docs/r/ssh_key.html.markdown
- website/docs/r/token.html.markdown
- website/docs/r/user_data.html.markdown
- website/docs/r/volume.html.markdown
- website/docs/r/volume_attachment.html.markdown
- website/scaleway.erb
YAML frontmatter key `sidebar_current` and method `sidebar_current` are deprecated.
More info: https://github.com/hashicorp/terraform-website#yaml-frontmatter
> doc: remove deprecated sidebar_current

- website/docs/r/compute_instance_server.html.markdown
- website/scaleway.erb
> doc: scaleway_compute_instance_server

- scaleway/resource_compute_instance_server.go
When assigning a running server to a placment group, it has to be rebooted to take effect
> fix: reboot on placement group change

- scaleway/resource_compute_instance_server.go
- scaleway/resource_compute_instance_server_test.go
Before:
```bash
$ grep "FAIL:" ~/Desktop/tf-test-TestAccScalewayComputeInstanceServer.log
--- FAIL: TestAccScalewayComputeInstanceServerRemoteExec (3.99s)
--- FAIL: TestAccScalewayComputeInstanceServerRootVolume1 (97.62s)
```
After:
```bash
$ grep "FAIL:" ~/Desktop/tf-test-TestAccScalewayComputeInstanceServer-without-fix.log
--- FAIL: TestAccScalewayComputeInstanceServerAdditionalVolumes2 (4.34s)
--- FAIL: TestAccScalewayComputeInstanceServerState2 (45.51s)
--- FAIL: TestAccScalewayComputeInstanceServerRemoteExec (2.52s)
--- FAIL: TestAccScalewayComputeInstanceServerRootVolume1 (100.82s)
--- FAIL: TestAccScalewayComputeInstanceServerState1 (123.24s)
--- FAIL: TestAccScalewayComputeInstanceServerUserData1 (132.82s)
--- FAIL: TestAccScalewayComputeInstanceServerUserData2 (138.27s)
```
> fix: resource_compute_instance_server tests

- scaleway/resource_k8s_cluster_beta.go
- scaleway/resource_k8s_pool_beta.go
> fix(k8s): do not update autoscaled pool size

- website/docs/r/account_ssh_key.html.markdown
- website/scaleway.erb
This is a quick typo fix for the documentation.
> Update and rename account_ssk_key.html.markdown to account_ssh_key.html

- scaleway/resource_instance_server.go
- scaleway/resource_instance_server_test.go
- website/docs/r/instance_server.html.markdown
This PR is a **BREAKING CHANGE** and:
- Remove the misnamed attribute `disable_public_ip` (with a "Please use disable_dynamic_ip instead" message)
- Replace it with a `disable_dynamic_ip` attribute
- Document the `disable_dynamic_ip` attribute
> break: rename disable_public_ip to disable_dynamic_ip

- go.mod
- go.sum
- scaleway/helpers_test.go
- scaleway/resource_instance_server.go
- scaleway/resource_instance_server_test.go
- vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/instance_sdk.go
- vendor/modules.txt
- website/docs/r/instance_server.html.markdown
> feat(instance): add ipv6 info on server resource

- scaleway/resource_account_ssh_key.go
- scaleway/resource_account_ssh_key_test.go
> fix(ssh_key): Trim ssh key before sending it to the API

- scaleway/helpers.go
- scaleway/resource_instance_server.go
- scaleway/resource_k8s_cluster_beta.go
- scaleway/resource_k8s_pool_beta.go
> fix: ignore case on instance types

- scaleway/provider.go
- scaleway/resource_instance_ip.go
- scaleway/resource_instance_ip_reverse_dns.go
- scaleway/resource_instance_ip_reverse_dns_test.go
- website/docs/r/instance_ip.html.markdown
- website/docs/r/instance_ip_reverse_dns.html.markdown
> feat(instance): create new resource instance_ip_reverse_dns

- scaleway/config.go
- scaleway/helpers.go
- scaleway/provider.go
Here example given in TF docs: https://github.com/terraform-providers/terraform-provider-kubernetes/pull/620/files
> chore: remove deprecated call to terraform.VersionString()

- scaleway/resource_instance_server.go
> fix(instance): read server image during import

- scaleway/helper_storage_object.go
- scaleway/resource_object_bucket.go
- website/docs/r/object_bucket.html.markdown
* Rename `getS3ClientWithRegionAndID` to `getS3ClientWithRegionAndName` as the resource ID il the name of the bucket.
* Use [aws-sdk-go constants](https://godoc.org/github.com/aws/aws-sdk-go/service/s3#pkg-constants) for `acl` attribute validatation function.
* Remove `bucket-owner-read` and `bucket-owner-full-control` canned ACL support as they are applied to objects and not buckets ([source](https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl)).
* Remove `log-delivery-write` canned ACL support as it is not supported in the aws-sdk-go. We could re-add it if needed. 
Closes #321
> fix(object): import bucket by name

- website/docs/index.html.markdown
scaleway_instance_volume.type is required
The total size of local-volume(s) of instances DEV1-L must be equal to 80GB
> doc: fix index example

- website/docs/d/image.html.markdown
- website/docs/d/volume.html.markdown
- website/docs/guides/migration_guide_v2.html.markdown
- website/docs/index.html.markdown
- website/docs/r/instance_server.html.markdown
- website/docs/r/ip_reverse_dns.html.markdown
- website/docs/r/k8s_pool_beta.html.markdown
- website/docs/r/security_group_rule.html.markdown
- website/docs/r/user_data.html.markdown
- website/docs/r/volume.html.markdown
- website/docs/r/volume_attachment.html.markdown
- Remove deprecated [interpolation syntax](https://www.terraform.io/docs/configuration-0-11/interpolation.html).
- Use `scaleway_instance_server.image = "ubuntu"` insteaf of an UUID.
- Improve example indentations
> doc: clean up documentation

- scaleway/resource_k8s_cluster_beta.go
- scaleway/resource_k8s_cluster_beta_test.go
- website/docs/r/k8s_cluster_beta.html.markdown
> fix(k8s): only recreate default pool on its update

- scaleway/resource_k8s_cluster_beta.go
- website/docs/r/k8s_cluster_beta.html.markdown
> feat(k8s): add feature gates and admission plugins

- scaleway/resource_k8s_cluster_beta.go
> fix(k8s): fix requirements for auto upgrade

- scaleway/helpers_k8s.go
- scaleway/resource_k8s_cluster_beta.go
- scaleway/resource_k8s_cluster_beta_test.go
- scaleway/resource_k8s_pool_beta.go
- scaleway/resource_k8s_pool_beta_test.go
- website/docs/r/k8s_cluster_beta.html.markdown
- website/docs/r/k8s_pool_beta.html.markdown
~~Depends on https://github.com/scaleway/scaleway-sdk-go/pull/312~~
~~To test with the *scaleway-sdk-go* patch from https://github.com/scaleway/scaleway-sdk-go/pull/312, 
run:~~
```
echo 'replace github.com/scaleway/scaleway-sdk-go => github.com/debovema/scaleway-sdk-go wait-for-nodes' >> go.mod
```
=> https://github.com/scaleway/scaleway-sdk-go/pull/312 was merged
> feat(k8s): wait for pool to be ready and add 'nodes' in its output

- scaleway/helpers_baremetal.go
- scaleway/resource_baremetal_server_beta.go
- website/docs/r/baremetal_server_beta.html.markdown
> feat(baremetal): export ips and domain

- scaleway/helpers.go
- scaleway/resource_instance_server.go
- scaleway/resource_instance_server_test.go
- scaleway/resource_ip.go
> fix(instance): add a diffSuppressFunc on image server attr

- scaleway/resource_instance_security_group.go
- scaleway/resource_instance_security_group_rules.go
Fixes
```go
scaleway/resource_instance_security_group_rules.go:68:7: Error return value of `d.Set` is not checked (errcheck)
d.Set("security_group_id", securityGroupZonedID)
^
scaleway/resource_instance_security_group_rules.go:75:7: Error return value of `d.Set` is not checked (errcheck)
d.Set("inbound_rule", inboundRules)
^
scaleway/resource_instance_security_group_rules.go:76:7: Error return value of `d.Set` is not checked (errcheck)
d.Set("outbound_rule", outboundRules)
```
> chore: linting error

- scaleway/helpers_lb.go
- scaleway/provider.go
- scaleway/resource_lb_certificate_beta.go
- scaleway/resource_lb_certificate_beta_test.go
- website/docs/r/lb_certificate_beta.html.markdown
- website/scaleway.erb
Fix #310
@jerome-quere the code is ready for testing, however Scaleway's current implementation presents some challenges (especially from integration tests point of view). 
When running tests, I was presented with some cryptic 400 bad request message. Rerunning it through the trace mode showed following:
```
{"name":"test-cert","letsencrypt":{"common_name":"main-domain.com","subject_alternative_name":[]}}
---------------------------------------------------------
[DEBUG] POST https://api.scaleway.com/lb/v1/regions/fr-par/lbs/76ac125b-55b9-4d88-8334-5d381d2f3758/certificates
2020/02/11 21:44:03 [DEBUG] 
--------------- Scaleway SDK RESPONSE 5 : ---------------
HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 188
Content-Security-Policy: default-src 'none'; frame-ancestors 'none' …
```
> feat: added certificate to load-balancer

- scaleway/resource_lb_frontend_beta.go
- website/docs/r/lb_frontend_beta.html.markdown
Fix #419
Note that I must break `acl` into its own section as the terraform website don't support > 2 nested list values. I took inspiration with [aws/ecs_cluster](https://www.terraform.io/docs/providers/aws/r/ecs_cluster.html).
> doc(lb): add ACL documentation

- scaleway/resource_instance_security_group.go
> fix(instance): fix SG on external rules plan

- README.md
* also link to Terraform homepage seemed redundant
> doc(README): add link to provider docs

- scaleway/helpers_k8s.go
- scaleway/resource_k8s_cluster_beta.go
> fix(k8s): use resource region on versions calls

- scaleway/resource_k8s_pool_beta.go
- website/docs/r/k8s_pool_beta.html.markdown
> fix(k8s): pool size and autoscaling

- scaleway/data_source_lb_ip_beta.go
- scaleway/data_source_lb_ip_beta_test.go
- scaleway/provider.go
- scaleway/resource_lb_ip_beta.go
- website/docs/d/lb_ip_beta.html.markdown
- website/scaleway.erb
> feat(lb): add LB IP data source

- website/docs/d/lb_ip_beta.html.markdown
> doc(ip): fixed typo in example

- scaleway/resource_rdb_instance_beta.go
- scaleway/resource_rdb_instance_beta_test.go
This is to allow converting an RDB instance to HA without recreating the resource.
This PR also contains minor fixes to the user_name and password fields which cannot be modified using the RDB instance API.
I plan on creating dedicated resources to manage users and databases in an upcoming PR.
To test I modified the acceptance test to also include an HA upgrade. This change will increase the test runtime by about 10 minutes, we can revert it if that’s too much of a time penalty. 
The whole test suite timed-out because of an unrelated issue, so I ran the Rdb acceptance tests only with the following:
```
~/github/terraform-provider-scaleway/scaleway% time TF_ACC=1 go test -v . -run "TestAccScalewayRdb*" -timeout=30m 
=== RUN   TestAccScalewayRdbInstanceBeta
=== PAUSE …
```
> Rdb: Allow RDB instance upgrade to HA without replacing the resource

- scaleway/provider.go
- scaleway/resource_rdb_instance_beta.go
- scaleway/resource_rdb_user_beta.go
- scaleway/resource_rdb_user_beta_test.go
- website/docs/r/rdb_instance_beta.html.markdown
- website/docs/r/rdb_user_beta.html.markdown
- website/scaleway.erb
This is to add a resource to manage RDB database users.
This allows to manage users admin permissions and passwords on RDB instances.
I've run the acceptance tests I've added:
```
17:12 paul@sca1 ~/github/terraform-provider-scaleway/scaleway% time TF_ACC=1 go test -v . -run "TestAccScalewayRdbUser*" -timeout=10m -count=1
=== RUN   TestAccScalewayRdbUserBeta
=== PAUSE TestAccScalewayRdbUserBeta
=== CONT  TestAccScalewayRdbUserBeta
--- PASS: TestAccScalewayRdbUserBeta (214.60s)
PASS
ok  	github.com/terraform-providers/terraform-provider-scaleway/scaleway	214.609s
TF_ACC=1 go test -v . -run "TestAccScalewayRdbUser*" -timeout=10m -count=1  6,05s user 0,81s system 3% cpu 3:37,17 total
```
Next step will be to allow creating instances without setting a user and password, so users can be fully …
> feat(rdb): add scaleway_rdb_user_resource_beta

- website/docs/d/instance_security_group.html.markdown
Fix typo in scaleway_instance_security_group documentation title.
> doc(instance): fix typo in security_group doc

- website/docs/r/instance_server.html.markdown
Better documentation until #534 is completed
> Add more detailled instructions using projects

- scaleway/data_source_instance_image.go
- scaleway/data_source_instance_security_group.go
- scaleway/data_source_instance_server.go
- scaleway/data_source_instance_volume.go
Instance API use fuzzyfinding for names, hence this change
Close #584
> fix(instance): fix datasource name queries

- docs/index.md
Fix the following error if only `SCW_ACCESS_KEY` and `SCW_SECRET_KEY` are configured
```
$ terraform init                         
Initializing the backend...                                                                                            
Backend configuration changed!                                                                                         
Terraform has detected that the configuration specified for the backend  
has changed. Terraform will now check for existing state in the backends.      
Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.                                 
Please see https://www.terraform.io/docs/backends/types/s3.html                                     
for more information about providing credentials. …
```
> doc: Documenting how to configure s3 backend with env vars

- .github/workflows/nightly.yml
I think I found out why the nightly test crashes, I think it's because of the cassettes.
https://github.com/scaleway/terraform-provider-scaleway/blob/master/.github/workflows/nightly.yml
basically here I don't indicate that I'm recording, so even if I'm in acceptance test mode, the cassettes interact with the real client.
So I think the best way to solve the problem is during the nightly to activate the recording of cassettes.
> chore: Enable cassette recording while playing acceptance tests

- .github/workflows/nightly.yml
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
> chore: disable fail-fast on github actions

- docs/resources/instance_security_group.md
- go.mod
- go.sum
- scaleway/helpers.go
- scaleway/resource_instance_security_group.go
- scaleway/resource_instance_security_group_test.go
- scaleway/testdata/instance-security-group-enable-default-security.cassette.yaml
In the console it is done by doing:
```
"enable_default_security": false
```
When doing a create.
> feat(instance): add support for enable_default_security

- .github/workflows/nightly.yml
We reuse our organization id as the default project id.
> fix(tests): add SCW_DEFAULT_PROJECT_ID in nightly test

- docs/guides/migration_guide_v2.md
The `provider.version` meta-argument is deprecated, the `required_provider` block need to be used instead. ([doc](https://www.terraform.io/docs/configuration/providers.html#version-an-older-way-to-manage-provider-versions))
> doc(guides): fix version argument in v1 to v2 migration guide

- docs/resources/instance_private_nic.md
As per the [test][1], the `scaleway_instance_private_nic` has a `mac_address` attribute that is missing from the documentation.
[1]: https://github.com/scaleway/terraform-provider-scaleway/blob/831de93490ddc5de298c009c7217027e3ff34dd7/scaleway/resource_instance_private_nic_test.go#L45
> Add missing mac_address attribute in the instance_private_nic documentation

- docs/resources/vpc_private_network.md
Small typo in the vpc_private_network resource doc.
> doc: fix typo tarraform -> terraform

- docs/resources/iot_network.md
- scaleway/provider.go
- scaleway/resource_iot_device.go
- scaleway/resource_iot_network.go
- scaleway/resource_iot_network_test.go
- scaleway/testdata/iot-network-minimal.cassette.yaml
Add implementation for IoT Hub Networks.
Based on #510 branch
> Iot hub networks

- scaleway/resource_k8s_cluster.go
Reverts scaleway/terraform-provider-scaleway#629
The GetOkExists method should be replaced by a propre replacement when available, we should keep the deprecate method meanwhile
> Revert "chore: remove usage of getokexists"

- .github/workflows/release.yml
- .github/workflows/unit-tests.yaml
Archive from @bflad
You may have noticed that Go 1.16 released yesterday and includes support for the new Apple M1 (“silicon”) hardware via a new release platform: darwin/arm64. If you are using goreleaser for provider releases, allow it to use the latest goreleaser version (most common), and update the release process to use Go 1.16, it will automatically include the new platform in releases. The Terraform Registry should ingress and serve them just fine, but please note that native Terraform CLI support for darwin/arm64 can be tracked in https://github.com/hashicorp/terraform/issues/27257 which will be updated with our timelines to prevent confusing errors for practitioners while the provider ecosystem starts rolling out this new platform.
One caveat to the typical goreleaser …
> chore: update go version to enable darwin/arm64 (m1) support

- docs/data-sources/k8s_cluster.md
- docs/resources/k8s_cluster.md
- scaleway/resource_k8s_cluster.go
- scaleway/resource_k8s_cluster_test.go
> feat(k8s): remove dashboard and ingress fields

- scaleway/resource_k8s_pool.go
BREAKING CHANGE: default runtime for k8s pool is now containerd instead of docker
> feat(k8s): change default runtime to containerd

- docs/resources/instance_snapshot.md
- go.mod
- go.sum
- scaleway/helpers_instance.go
- scaleway/provider.go
- scaleway/resource_instance_snapshot.go
- scaleway/resource_instance_snapshot_test.go
- scaleway/testdata/instance-snapshot-block-volume.cassette.yaml
- scaleway/testdata/instance-snapshot-rename-snapshot.cassette.yaml
- scaleway/testdata/instance-snapshot-server-with-block-volume.cassette.yaml
- scaleway/testdata/instance-snapshot-server.cassette.yaml
We need to add support for updating a snapshot to handle snapshot renaming
> feat(instance): add support for snapshot

- .github/workflows/nightly.yml
- scaleway/data_source_rdb_instance_test.go
```bash
$ grep -r "func TestAccScaleway" scaleway/  | cut -d " " -f 2 |cut -d "(" -f 1 | sed -e 's/TestAccScaleway//' -e "s/DataSource//" |sort |grep -v -e "^Account" -e "^Baremetal" -e "^Instance" -e "^K8S" -e "^Lb" -e "^Object" -e "^Rdb" -e "^Registry" -e "^VPC"
IotDevice_Minimal         
IotHub_Minimal
IotNetwork_Minimal      
IotRoute_Minimal                 
MarketplaceImage_Basic
RDBInstance_Basic
```
> ci(nightly): Some products are not tested

- scaleway/resource_object_bucket_test.go
- scaleway/testdata/object-bucket-cors-empty-origin.cassette.yaml
Confirmed with s3cmd: 
```bash
$ s3cmd  setcors cors.xml s3://test-cors-jsh-2
WARNING: Retrying failed request: /?cors (500 (InternalError): We encountered an internal error. Please try again.)
WARNING: Waiting 3 sec...
WARNING: Retrying failed request: /?cors (500 (InternalError): We encountered an internal error. Please try again.)
WARNING: Waiting 6 sec...
```
With the following cors.xml
```xml
<CORSConfiguration>
<CORSRule>
<AllowedOrigin></AllowedOrigin>
<AllowedMethod>GET</AllowedMethod>
<MaxAgeSeconds>3000</MaxAgeSeconds>
<ExposeHeader>Etag</ExposeHeader>
</CORSRule>
</CORSConfiguration>
```
Note: [s3 api](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CORSRule.html) require  AllowedOrigins to be required -
> test(s3/cors): Setting an empty allowed origin is not allowed

- scaleway/resource_instance_volume.go
- scaleway/testdata/instance-volume-resize-block.cassette.yaml
The test was failing although the volume was properly resized.
The provider was waiting **before** resizing the volume.
```bash
--- PASS: TestAccScalewayInstanceVolume_ResizeBlock (18.26s)                                                           
PASS                                                                                                                   
ok      github.com/scaleway/terraform-provider-scaleway/scaleway        18.271s  
```
> fix(instance/volume): Wait for the volume after resizing it

- scaleway/resource_instance_volume.go
- scaleway/testdata/instance-volume-from-volume.cassette.yaml
When creating a volume from a snapshot or with a copy: the attribute "size_in_db" should not be read as it's conflicting with this feature
The test was failing:
```bash
resource_instance_volume_test.go:89: Step 1/1 error: After applying this test step, the plan was not empty.                                                                                                                               
stdout:                                                                                                        
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:    
~ resource "scaleway_instance_volume" "test2" {
id              = …
```
> fix(Instance/Volume): size_in_db should not be set when importing volume

- scaleway/resource_instance_placement_group_test.go
- scaleway/testdata/instance-placement-group-basic.cassette.yaml
Like https://github.com/scaleway/terraform-provider-scaleway/commit/c5df89b4bc70e01021c099dcd4de01b2dfb4d7da
cassette seems to have some difficulties to match the right requests.
In the previous configuration the test was doing 2 stuffs at the same time.
* Update a placement group with default values to enforced
* Downgrade an enforced placement group to default 
Let's do this in 3 steps with the same placements group.
> test: simplify the test to avoid random results with cassete recording

- scaleway/resource_k8s_pool.go
Added ForceNew, on cluster_id to force node-pool destroy/recreated when cluster is detroyed/recreated
> fix (k8s): Added ForceNew on cluster_id nodepool

- scaleway/resource_rdb_instance.go
Update the instance creation timeout to match the RDB one instead of InstanceServer
> fix: increase rdb instance creation timeout to 15m

- docs/resources/iot_device.md
Replace "scaleway_iot_hub_device" with "scaleway_iot_device"
> fix(docs) wrong name for resource iot_device

- docs/index.md
- scaleway/provider.go
With the arrival of the new project functionality on the platform, I ended up needing to use two authenticated `scaleway` providers on two different projects within the same Terraform project.
My intention here is to provide a way to easily manage multiple profiles declared in the Scaleway CLI static configuration file in the same way as with [the AWS provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#shared-credentials-file) 
```hcl
terraform {
required_providers {
scaleway = {
source  = "local/scaleway/scaleway"
version = "~> 2.1.0"
}
}
required_version = ">= 0.13"
}
provider "scaleway" {
profile = "myProjectProfile"
}
provider "scaleway" {
alias   = "dns"
profile = "myDnsProfile"
}
resource "scaleway_domain_record" "project_domain_record" {
provider = …
```
> feat(provider): add profile name from configuration file support

- README.md
Hello !
It looks like the existing Slack link in the README is not usable: I get a default Slack login page upon visiting the link.
I found a link to Scaleway's Community Slack and replaced the existing one, as well as edit the link under `#terraform` to fit with the pattern I found in https://github.com/scaleway/scaleway-sdk-go#reach-us
> doc(README): fix Slack links (registering + terraform channel)

- scaleway/resource_k8s_cluster.go
The `k8sGetLatestVersionFromMinor` call is the first interaction with the scaleway API when auto_update is enabled and the version is set to a x.y minor version. 
But a possible error message from the API call is never logged. So if you have a typo in your credentials or forgot to add the project_id to the provider, you are confronted with the error message "minor version x.y must be used with auto upgrade enable".
This PR just reports the error from `k8sGetLatestVersionFromMinor` to the user.
> fix(k8s): return error code from k8sGetLatestVersionFromMinor call

- .goreleaser.yml
- go.mod
- main.go
The major version of the module has been tagged as a `v2` module, but the `go.mod` wasn't updated.
> update to use v2 imports

- scaleway/resource_domain_record.go
Related to https://github.com/scaleway/terraform-provider-scaleway/issues/1023
When importing a domain record, it goes into the first `if` : https://github.com/scaleway/terraform-provider-scaleway/blob/master/scaleway/resource_domain_record.go#L267
By the end, the `dnsZone` that is parsed is never set : https://github.com/scaleway/terraform-provider-scaleway/blob/master/scaleway/resource_domain_record.go#L340
I suggest here setting the `dns_zone` at the end, feedback welcome if you see other ways to fix this issue.
Tested locally on Terraform 1.0.7.
> fix(domain-record): Add dns_zone to tfstate when using terraform import

- scaleway/resource_apple_silicon_server.go
After a create, the callback for reading was the one of RDB instead of Apple Silicon :)
> Fix(AppleSilicon): fix Apple Silicon read

- scaleway/data_source_vpc_public_gateway.go
- scaleway/helpers_vpcgw.go
- scaleway/resource_vpc_gateway_network.go
- scaleway/resource_vpc_gateway_network_test.go
- scaleway/resource_vpc_public_gateway.go
- scaleway/resource_vpc_public_gateway_dhcp.go
- scaleway/resource_vpc_public_gateway_dhcp_test.go
- scaleway/resource_vpc_public_gateway_ip.go
- scaleway/resource_vpc_public_gateway_ip_test.go
- scaleway/resource_vpc_public_gateway_pat_rule.go
- scaleway/resource_vpc_public_gateway_pat_rule_test.go
- scaleway/resource_vpc_public_gateway_test.go
- scaleway/testdata/data-source-vpc-public-gateway-basic.cassette.yaml
- scaleway/testdata/data-source-vpc-public-gateway-dhcp-basic.cassette.yaml
- scaleway/testdata/data-source-vpc-public-gateway-ip-basic.cassette.yaml
- scaleway/testdata/rdb-instance-private-network-dhcp.cassette.yaml
- scaleway/testdata/rdb-instance-private-network.cassette.yaml
- scaleway/testdata/vpc-gateway-network-basic.cassette.yaml
- scaleway/testdata/vpc-gateway-network-without-dhcp.cassette.yaml
- scaleway/testdata/vpc-public-gateway-attach-to-ip.cassette.yaml
- scaleway/testdata/vpc-public-gateway-basic.cassette.yaml
- scaleway/testdata/vpc-public-gateway-dhcp-basic.cassette.yaml
- scaleway/testdata/vpc-public-gateway-ip-basic.cassette.yaml
- scaleway/testdata/vpc-public-gateway-pat-rule-basic.cassette.yaml
- scaleway/testdata/vpc-public-network-basic.cassette.yaml
- scaleway/testdata/vpc-public-network-without-dhcp.cassette.yaml
The v1 API is a drop-in replacement for v1beta1.
> chore(vpcgw): migrate from v1beta1 to v1

- scaleway/resource_instance_server.go
Change the computed volume size from serverType.VolumesConstraint.MinSize to serverType.VolumesConstraint.MaxSize. It's an adaptation to the loose constraints where serverType.VolumesConstraint.MinSize is 0.
> Change the computed volume size of an instance

- docs/data-sources/domain_record.md
- docs/resources/domain_record.md
- scaleway/helpers_domain.go
- scaleway/resource_domain_record.go
- scaleway/resource_domain_record_test.go
- scaleway/resource_instance_ip_reverse_dns_test.go
- scaleway/testdata/data-source-domain-record-basic.cassette.yaml
- scaleway/testdata/domain-record-basic.cassette.yaml
- scaleway/testdata/domain-record-basic2.cassette.yaml
- scaleway/testdata/domain-record-geo-ip.cassette.yaml
- scaleway/testdata/domain-record-http-service.cassette.yaml
- scaleway/testdata/domain-record-view.cassette.yaml
- scaleway/testdata/domain-record-weighted.cassette.yaml
- scaleway/testdata/instance-ip-reverse-dns-basic.cassette.yaml
* Fix schema domain record
* Fix read method
* Fix helpers on TXT record DATA
* Fix setter ID for resource domain_record
* Fix add missing attributes to update process
> Fix(domain-record): TXT record and helpers

- docs/resources/redis_cluster.md
- scaleway/helpers_redis.go
- scaleway/resource_redis_cluster.go
- scaleway/resource_redis_cluster_test.go
- scaleway/testdata/redis-cluster-acl.cassette.yaml
> feat(redis): add redis acl

- docs/resources/lb.md
- scaleway/helpers_lb.go
- scaleway/resource_lb.go
- scaleway/resource_lb_test.go
- scaleway/testdata/lblb-with-ip.cassette.yaml
- scaleway/testdata/lblb-with-multi-configs.cassette.yaml
- scaleway/testdata/lblb-with-several-private-networks.cassette.yaml
- Add check on load balancer private network attachement status
- Add context on missing queries
- Update Test
- Update Cassettes
- Update LB documentation
Related to #1209
> fix(lb): check private network status

- docs/resources/rdb_instance.md
> doc(rdb): add details for rdb instance settings option

- scaleway/resource_rdb_instance.go
- scaleway/resource_vpc_public_gateway_dhcp.go
GetOk returned false for the ok value when the boolean was false, making the schema value not passed to the api
> fix: remove GetOk usage with optional boolean

- scaleway/resource_apple_silicon_server.go
- scaleway/resource_baremetal_server.go
- scaleway/resource_container_namespace.go
- scaleway/resource_domain_record.go
- scaleway/resource_function_namespace.go
- scaleway/resource_instance_private_nic.go
- scaleway/resource_instance_server.go
- scaleway/resource_instance_snapshot.go
- scaleway/resource_instance_volume.go
- scaleway/resource_iot_network.go
- scaleway/resource_iot_routes.go
- scaleway/resource_k8s_cluster.go
- scaleway/resource_k8s_pool.go
- scaleway/resource_lb.go
- scaleway/resource_lb_backend.go
- scaleway/resource_lb_certificate.go
- scaleway/resource_lb_frontend.go
- scaleway/resource_lb_ip.go
- scaleway/resource_rdb_acl.go
- scaleway/resource_rdb_database.go
- scaleway/resource_rdb_instance.go
- scaleway/resource_rdb_privilege.go
- scaleway/resource_rdb_user.go
- scaleway/resource_redis_cluster.go
- scaleway/resource_registry_namespace.go
- scaleway/resource_vpc_gateway_network.go
- scaleway/resource_vpc_public_gateway.go
- scaleway/resource_vpc_public_gateway_dhcp_reservation.go
- scaleway/resource_vpc_public_gateway_pat_rule.go
> fix: add timeout values in schema when they're being used

- scaleway/resource_baremetal_server.go
- scaleway/resource_instance_ip.go
- scaleway/resource_instance_placement_group.go
- scaleway/resource_instance_server.go
- scaleway/resource_k8s_cluster.go
- scaleway/resource_k8s_pool.go
- scaleway/resource_rdb_instance.go
- scaleway/resource_vpc_public_gateway.go
On update, list of strings were not updated if it was empty. The function `expandStrings` would just return `nil` as it is the zero value for slice.
> fix: update of strings list

- scaleway/data_source_iam_application.go
- scaleway/data_source_iam_application_test.go
- scaleway/provider.go
- scaleway/testdata/data-source-iam-application-basic.cassette.yaml
Adding IAM applications data source.
We still have to set the organization_id manually in order to send List requests (as for other datasources), but this will be fixed in the future. --> see [issue](https://github.com/scaleway/terraform-provider-scaleway/issues/1337)
> feat(iam): add iam application datasource

- scaleway/resource_instance_image_test.go
- scaleway/testdata/instance-image-block-volume.cassette.yaml
- scaleway/testdata/instance-image-server-with-block-volume.cassette.yaml
- scaleway/testdata/instance-image-server-with-local-volume.cassette.yaml
- scaleway/testdata/instance-image-server.cassette.yaml
To fix the error "cannot snapshot volume ***: cannot create a ro disk from an empty disk" in the nightly tests, I removed state "stopped" in tests involving servers.
> fix(instance_image): fix nightly tests

- docs/data-sources/vpc_gateway_network.md
- scaleway/data_source_vpc_gateway_network.go
- scaleway/data_source_vpc_gateway_network_test.go
- scaleway/provider.go
- scaleway/testdata/data-source-vpc-gateway-network-basic.cassette.yaml
> feat(gateway_network): add vpc gateway network data source

- scaleway/resource_vpc_public_gateway_dhcp.go
Errors reported on scaleway community slack
```
The following problems may be the cause of any confusing errors from downstream operations:
- .dns_servers_override: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
- .dns_search: planned value cty.ListValEmpty(cty.String) for a non-computed attribut
```
> fix(vpcgw_dhcp): set dns search and servers_override fields to computed

- scaleway/resource_redis_cluster.go
* Fix on Redis ACL resource. The `DiffSuppressDiff` looks not work on nested Schema.
> fix(redis): add validation method

- scaleway/resource_iam_policy_test.go
Organization ID is mocked because this resource needs it as a required field.
Without overriding it, tests would fail when checking organization_id. 
If skipping organization_id check and not overriding it, test would still fail with a non empty plan because of changing orgID
> tests(iam_policy): override orgID for cassette run only

- .github/workflows/acceptance-tests.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/coverage.yml
- .github/workflows/documentation.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .github/workflows/tfproviderlint.yml
- .github/workflows/unit-tests.yaml
```
Node.js 12 actions are deprecated.
For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16: actions/setup-go, actions/checkout, actions/checkout
```
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> ci: bump actions versions

- docs/resources/lb_frontend.md
Hello,
I believe an important piece of information is missing from the documentation about certificates attached to load balancers.
If the `create_before_destroy` lifecycle rule is not set on a certificate attached to a load balancer, the user will get the error message: "operation was rejected because the certificate is used on a frontend" when trying to change the certificate (add a domain for instance).
Having this rule fixes the issue. I had the idea to set it because it is the same with DigitalOcean, but they have this on their doc:
I added the setting in load balancer code examples, but it might also be useful to add it on `lb_certificate` page, or a note about it.
Best,
~Nico
> docs: add lifecycle in lb_certificate example

- docs/resources/lb_certificate.md
Fix #1550. A lifecycle instruction is necessary to replace a certificate that is attached to a load balancer. See #1546.
> docs: add lifecycle note for certificate

- scaleway/resource_object_bucket.go
Filter used an `And` filter with a single tag in it, this was not valid s3 xml
> fix(bucket): filter lifecycle without operator when using a single tag

- scaleway/helpers_object.go
- scaleway/resource_object_bucket_website_configuration.go
Using `s3manager.GetBucketRegionWithClient` was always returning "us-east-1" as a region
> fix(object): fix region retrieval for object bucket website endpoint

- docs/resources/instance_server.md
> docs(instance): add examples to instance_server with root_volume usage

- scaleway/retryable_transport.go
It would be great to add tests for requests error and be sure we always pass error when needed
Before this fix, error when a request was not found in cassette was eaten by the errorHandler
> fix(provider): pass error when request failed to execute in retryclient

- go.mod
- go.sum
- scaleway/helpers.go
- scaleway/resource_vpc_gateway_network.go
> feat: add helper to retry on transient state error

- docs/index.md
This PR fixes a typo in all scoped variables in documentation.
> Fix minor typos in scoped environment variables (`s/scopped/scoped/g`)

- docs/resources/k8s_cluster.md
- scaleway/data_source_k8s_cluster_test.go
- scaleway/data_source_k8s_pool_test.go
- scaleway/resource_k8s_cluster.go
- scaleway/resource_k8s_cluster_test.go
- scaleway/resource_k8s_pool_test.go
- scaleway/testdata/data-source-k8s-cluster-basic.cassette.yaml
- scaleway/testdata/data-source-k8s-pool-basic.cassette.yaml
- scaleway/testdata/k8s-cluster-auto-upgrade.cassette.yaml
- scaleway/testdata/k8s-cluster-autoscaling.cassette.yaml
- scaleway/testdata/k8s-cluster-basic.cassette.yaml
- scaleway/testdata/k8s-cluster-multicloud.cassette.yaml
- scaleway/testdata/k8s-cluster-oidc.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-basic.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-kubelet-args.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-placement-group.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-upgrade-policy.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-wait.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-zone.cassette.yaml
As suggested in issue [#959](https://github.com/scaleway/terraform-provider-scaleway/issues/959), the cluster attribute "delete_additional_resources" is now required instead of optional.
> feat(k8s) - breaking - make "delete_additional_resources" required

- docs/resources/object_bucket.md
- docs/resources/object_bucket_acl.md
- scaleway/resource_object_bucket.go
The previous deprecation message was not clear from a user point of view. Update it for users to be clearer.
Also update the docs of the provider.
> docs(bucket): make acl deprecation message clearer

- scaleway/data_source_registry_namespace_test.go
- scaleway/resource_container_namespace_test.go
- scaleway/resource_registry_namespace_test.go
- scaleway/testdata/container-namespace-destroy-registry.cassette.yaml
- scaleway/testdata/data-source-registry-namespace-basic.cassette.yaml
- scaleway/testdata/registry-namespace-basic.cassette.yaml
Registry is currently slow to delete namespaces, set region to pl-waw as a workaround while waiting for it to be fixed
> tests: change region in tests that require registry ns deletion

- docs/data-sources/k8s_version.md
- scaleway/data_source_k8s_version.go
- scaleway/data_source_k8s_version_test.go
- scaleway/provider.go
- scaleway/testdata/data-source-k8s-version-basic.cassette.yaml
This PR adds the datasource `scaleway_k8s_version`
Closes #1762
> feat(k8s): add k8s version data source

- scaleway/resource_domain_record.go
Whenever a record that doesn't exist is still present in Terraform state, we are stuck with the read failing because of a 403 error. 403 is used to indicate both that the record doesn't exist or that it exist be we are not allowed to access it.
This happens during normal operations because the deletion of a DNS record regularly fails with another error (that I have yet to investigate).
> fix(dns): API returns 403 instead of 404 on missing record

- scaleway/resource_domain_record.go
Fix `waiting for DNS failed: NoSuchDNSZone` error on record deletion.
> fix(domain): correctly check for NoSuchDNSZone error code

- docs/data-sources/k8s_version.md
- scaleway/data_source_k8s_version.go
- scaleway/data_source_k8s_version_test.go
- scaleway/testdata/data-source-k8s-version-latest.cassette.yaml
Closes #1805
NB: the test added in this PR will have to be updated as soon as a new k8s version is available otherwise it will fail.
> feat(k8s): k8s version datasource supports "latest" as a value

- scaleway/data_source_rdb_instance.go
When trying to import a RDB instance, the name parameter is directly passed to the API which treat it as a pattern instead of an exact match leading to a multiple instance with the name error if other instance contains the name of the searched instance.
This PR adds an additional step of matching to ensure only exact match are returned.
The code is heavily inspired by what is donne inside the `scaleway_instance_server` data source.
> Fix scaleway_rdb_instance using name as a pattern instead of an exact match

- scaleway/resource_k8s_cluster_test.go
- scaleway/testdata/k8s-cluster-private-network.cassette.yaml
The use of the TrimLeft function was causing some issues in the tests, and it turned out that the ID didn't even have to be trimmed.
> fix(k8s): fix K8SCluster_PrivateNetwork test 2

- scaleway/resource_k8s_pool_test.go
- scaleway/testdata/k8s-cluster-pool-private-network.cassette.yaml
Adds a test for Kapsule private networks that checks if the instances of the pool are actually inside the private network like they are supposed to.
> test(k8s): add test K8SCluster_PoolPrivateNetwork

- scaleway/helpers_object.go
The project ID was not used if defined in the provider configuration because it's considered as the default one.
> feat(object): force project id in access key even if it's the default

- scaleway/data_source_k8s_version_test.go
- scaleway/resource_k8s_pool_test.go
- scaleway/testdata/data-source-k8s-version-basic.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-private-network.cassette.yaml
Fixes the latest problem in the nightly tests (k8s version 1.26.2 supports 3 CNIs instead of 2)
+ small fix : changes the names in a test to fix a small unrelated problem that sometimes occur locally (`scaleway-sdk-go: invalid argument(s): name does not respect constraint, cluster name must be unique across the project`)
> test(k8s): fixed expected cnis + duplicate name in tests

- scaleway/helpers_k8s.go
- scaleway/resource_k8s_cluster.go
- scaleway/resource_k8s_cluster_test.go
- scaleway/testdata/k8s-cluster-private-network.cassette.yaml
Changing the Private Network after the creation of the cluster is not possible, therefore the `private_network_id` field was marked as ForceNew. But since it could result in the loss of data, we prefer to change things up a bit and add more warning before triggering the destruction and recreation of the cluster. 
No PNID -> PNID : migrates the cluster to the private network
PNID -> no PNID : warns before forcing new cluster
PNID a -> PNID b : warns before forcing new cluster
If no PNID is specified when creating a cluster, this still creates a legacy cluster (without PN)
Closes  #1947
> fix(k8s): changes in PN should not always result in ForceNew

- cmd/tftemplate/helpers.go.tmpl
- cmd/tftemplate/main.go
- cmd/tftemplate/models/resource.go
- cmd/tftemplate/templates.go
- cmd/tftemplate/waiters.go.tmpl
Added two new prompt, example with new block volume resource:
```
? API name (function, instance, container) block
? Resource name (FunctionNamespace, InstanceServer) BlockVolume
?  zone
? Generate helpers ? Will override scaleway/helpers_{api}.go (y/N) Yes
? Generate helpers ? Will be added to scaleway/helpers_{api}.go (Y/n) Yes
```
> feat(tftemplate): generate helpers with resource

- scaleway/resource_iam_api_key_test.go
- scaleway/resource_iam_application_test.go
- scaleway/resource_iam_group_test.go
- scaleway/resource_iam_policy_test.go
Sweepers are currently broken in nightly tests because of required organization ID
> tests(iam): get organization id from client in sweepers

- scaleway/resource_vpc_private_network.go
ForceNew option is missing on vpc_id argument.
> Set ForceNew on vpc_id argument of scaleway_vpc ressource

- scaleway/resource_vpc_private_network.go
I think the provider should remove the vpc_private_network resource from the state only if not found, so we'll be able to retry the removal if there is another type of error.
> Remove resource vpc_private_network only on 404

- docs/resources/container.md
Hey team!
We got some feedback from one user that the default protocol in the Terraform container example was error-inducing. We agreed, because h2c is only useful for certain use cases (http2, plaintext grpc) which most users are not after. So IMO, it would be better to switch it to HTTP for the time being because it fits most use cases.
What do you think?
Cheers!
> docs(container): change example protocol from h2c to http1

- docs/resources/k8s_pool.md
- scaleway/resource_k8s_pool.go
- scaleway/resource_k8s_pool_test.go
- scaleway/testdata/k8s-cluster-pool-public-ip-disabled.cassette.yaml
The k8s API just got a new field `public_ip_disabled` which allows users to choose if they want their pools to be given a public IP or not. 
It should be integrated to the `scaleway_k8s_pool` resource.
> feat(k8s): integrate `public_ip_disabled` field

- scaleway/resource_instance_server.go
- scaleway/testdata/data-source-vpc-public-gateway-dhcp-reservation-basic.cassette.yaml
- scaleway/testdata/data-source-vpc-public-gateway-dhcp-reservation-static.cassette.yaml
- scaleway/testdata/instance-server-private-network.cassette.yaml
- scaleway/testdata/lblb-different-locality-ipid.cassette.yaml
- scaleway/testdata/lblb-invalid-static-config.cassette.yaml
- scaleway/testdata/lblb-with-private-networks-on-dhcp-config.cassette.yaml
- scaleway/testdata/vpc-public-gateway-dhcp-entry-basic.cassette.yaml
- scaleway/testdata/vpc-public-gateway-pat-rule-with-instance.cassette.yaml
Delete private-nic before server when managed by `instance_server` resource.
Useful for the workflow:
- Delete Server
- Delete PN
It would fail because the PN was not empty yet
> fix(instance_server): detach pn on server deletion

- scaleway/data_source_k8s_pool_test.go
- scaleway/testdata/data-source-k8s-pool-basic.cassette.yaml
Fixes the current error in the nightly tests. Private networks were added in the tests in #2172 but I missed the data source test for the pools.
> test(k8s): fix nightly tests: add PN to data source pool test too

- docs/resources/rdb_instance.md
- scaleway/resource_rdb_instance.go
- scaleway/testdata/data-source-rdb-acl-basic.cassette.yaml
- scaleway/testdata/data-source-rdb-database-backup-basic.cassette.yaml
- scaleway/testdata/data-source-rdb-database-basic.cassette.yaml
- scaleway/testdata/data-source-rdb-instance-basic.cassette.yaml
- scaleway/testdata/data-source-rdb-privilege-basic.cassette.yaml
- scaleway/testdata/rdb-acl-basic.cassette.yaml
- scaleway/testdata/rdb-database-backup-basic.cassette.yaml
- scaleway/testdata/rdb-database-basic.cassette.yaml
- scaleway/testdata/rdb-database-manual-delete.cassette.yaml
- scaleway/testdata/rdb-instance-backup-schedule.cassette.yaml
- scaleway/testdata/rdb-instance-basic.cassette.yaml
- scaleway/testdata/rdb-instance-capitalize.cassette.yaml
- scaleway/testdata/rdb-instance-init-settings.cassette.yaml
- scaleway/testdata/rdb-instance-private-network-dhcp.cassette.yaml
- scaleway/testdata/rdb-instance-private-network-update.cassette.yaml
- scaleway/testdata/rdb-instance-private-network.cassette.yaml
- scaleway/testdata/rdb-instance-settings.cassette.yaml
- scaleway/testdata/rdb-instance-volume.cassette.yaml
- scaleway/testdata/rdb-instance-with-cluster.cassette.yaml
- scaleway/testdata/rdb-privilege-basic.cassette.yaml
- scaleway/testdata/rdb-read-replica-basic.cassette.yaml
- scaleway/testdata/rdb-read-replica-different-zone.cassette.yaml
- scaleway/testdata/rdb-read-replica-multiple-endpoints.cassette.yaml
- scaleway/testdata/rdb-read-replica-private-network.cassette.yaml
- scaleway/testdata/rdb-read-replica-update.cassette.yaml
- scaleway/testdata/rdb-user-basic.cassette.yaml
Closes #2046 
The provider didn't allow changes to `node_type` or `volume_size_in_gb` once the instance reached `disk_full` status. This is because both these attributes belong in the upgrades category and it tried to perform the updates before, which failed since the resource is in a transient state.
This PR fixes the issue by performing the upgrades first and adds a bit of documentation on how to deal with a `disk_full` situation with Terraform.
> feat(rdb): allow actions to handle a full disk situation

- scaleway/resource_k8s_pool.go
- scaleway/resource_k8s_pool_test.go
- scaleway/testdata/data-source-k8s-cluster-basic.cassette.yaml
- scaleway/testdata/data-source-k8s-pool-basic.cassette.yaml
- scaleway/testdata/k8s-cluster-auto-upgrade.cassette.yaml
- scaleway/testdata/k8s-cluster-autoscaling.cassette.yaml
- scaleway/testdata/k8s-cluster-basic.cassette.yaml
- scaleway/testdata/k8s-cluster-multicloud.cassette.yaml
- scaleway/testdata/k8s-cluster-oidc.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-basic.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-kubelet-args.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-placement-group.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-private-network.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-public-ip-disabled.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-size.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-upgrade-policy.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-wait.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-zone.cassette.yaml
- scaleway/testdata/k8s-cluster-private-network.cassette.yaml
- scaleway/testdata/k8s-cluster-type-change.cassette.yaml
There is an error 500 in the PoolPublicIPDisabled test that only occurred in the CI and not when recording the cassettes locally. We did not wait for the pool after deleting it, and that could cause issues when recreating a pool with the same name too soon (e.g. in the case of ForceNew)
> fix(k8s): fix 500 in PoolPublicIPDisabled test

- scaleway/data_source_k8s_cluster_test.go
- scaleway/data_source_k8s_pool_test.go
- scaleway/resource_k8s_cluster_test.go
- scaleway/resource_k8s_pool_test.go
- scaleway/testdata/data-source-k8s-cluster-basic.cassette.yaml
- scaleway/testdata/data-source-k8s-pool-basic.cassette.yaml
- scaleway/testdata/k8s-cluster-auto-upgrade.cassette.yaml
- scaleway/testdata/k8s-cluster-autoscaling.cassette.yaml
- scaleway/testdata/k8s-cluster-basic.cassette.yaml
- scaleway/testdata/k8s-cluster-multicloud.cassette.yaml
- scaleway/testdata/k8s-cluster-oidc.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-basic.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-kubelet-args.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-placement-group.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-private-network.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-public-ip-disabled.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-size.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-upgrade-policy.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-wait.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-zone.cassette.yaml
- scaleway/testdata/k8s-cluster-private-network.cassette.yaml
- scaleway/testdata/k8s-cluster-type-change.cassette.yaml
In an attempt to fix the random errors in the K8s nightly tests, listing every resource that was used in each test in CheckDestroy could make the sweeping process better.
> test(k8s): CheckDestroy lists all resources used in test

- scaleway/resource_object_bucket_acl_test.go
- scaleway/testdata/object-bucket-acl-grantee.cassette.yaml
TestAccScalewayObjectBucketACL_Grantee was failing because the second step used to overwrite the previous ACL, stripping the owner of his rights. This PR adds the owner to the second step's ACL.
> test(object): fix nightly ACL_Grantee

- scaleway/data_source_k8s_cluster_test.go
- scaleway/data_source_k8s_pool_test.go
- scaleway/resource_k8s_cluster_test.go
- scaleway/resource_k8s_pool_test.go
- scaleway/testdata/data-source-k8s-cluster-basic.cassette.yaml
- scaleway/testdata/data-source-k8s-pool-basic.cassette.yaml
- scaleway/testdata/k8s-cluster-auto-upgrade.cassette.yaml
- scaleway/testdata/k8s-cluster-autoscaling.cassette.yaml
- scaleway/testdata/k8s-cluster-basic.cassette.yaml
- scaleway/testdata/k8s-cluster-multicloud.cassette.yaml
- scaleway/testdata/k8s-cluster-oidc.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-basic.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-kubelet-args.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-placement-group.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-public-ip-disabled.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-size.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-upgrade-policy.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-wait.cassette.yaml
- scaleway/testdata/k8s-cluster-pool-zone.cassette.yaml
- scaleway/testdata/k8s-cluster-private-network.cassette.yaml
- scaleway/testdata/k8s-cluster-type-change.cassette.yaml
In an attempt to fix the random deletion errors in the nightly tests, we should declare the CheckDestroy functions in the order they should be called.
Also TestAccScalewayK8SCluster_PoolPrivateNetwork serves no purpose now that all clusters must have a private network.
> test(k8s): reorder CheckDestroy

- scaleway/helpers_k8s.go
The k8s nightly tests currently fail with the error message `cluster xxx-xx-xxx has state deleted, wants deleted` because the only way to exit the waitK8SClusterDeleted function without an error is with a 404. But sometimes the cluster has state `deleted` but does not return a 404 right away, prompting this error message.
This can be fixed by checking the status before returning the error.
> fix(k8s): check status before returning error

- scaleway/resource_domain_record.go
- scaleway/testdata/data-source-domain-record-basic.cassette.yaml
- scaleway/testdata/domain-record-arobase.cassette.yaml
- scaleway/testdata/domain-record-basic.cassette.yaml
- scaleway/testdata/domain-record-basic2.cassette.yaml
- scaleway/testdata/domain-record-cname.cassette.yaml
- scaleway/testdata/domain-record-geo-ip.cassette.yaml
- scaleway/testdata/domain-record-http-service.cassette.yaml
- scaleway/testdata/domain-record-srv-zone.cassette.yaml
- scaleway/testdata/domain-record-view.cassette.yaml
- scaleway/testdata/domain-record-weighted.cassette.yaml
Always send the full record content when updating it to avoid losing dynamic types (geoIP, etc.)
> fix(dom): update DNS record with dynamic data

- scaleway/helpers_object.go
- scaleway/resource_object_bucket.go
> fix(object): getting a 403 when reading bucket should not exit the provider

- scaleway/resource_k8s_cluster.go
This PR add a warning if cluster type is not prefixed by kapsule or multicloud, instead of returning an error.
> feat(k8s): add warning if cluster type is not prefixed by kapsule or multicloud

- scaleway/resource_mnq_nats_credentials.go
> fix(nats_credentials): read account-id and supress locality diff

- docs/resources/iam_policy.md
> docs(iam_policy): add example of rule for all projects

- scaleway/resource_k8s_cluster.go
We should not send a warning about a potentially invalid cluster type when it has not been set.
> fix(k8s): empty string is a valid cluster type

- .github/workflows/tfproviderlint.yml
A fork was previously used as the official version was broken
> ci: use official tfproviderlint

- docs/data-sources/object_bucket_policy.md
- docs/index.md
- docs/resources/object.md
- docs/resources/object_bucket_acl.md
- docs/resources/object_bucket_lock_configuration.md
- docs/resources/object_bucket_policy.md
- docs/resources/object_bucket_website_configuration.md
> doc(object): document project ID for bucket child resources

- go.mod
- go.sum
- scaleway/resource_rdb_read_replica.go
- scaleway/testdata/data-source-lb-ips-basic.cassette.yaml
- scaleway/testdata/data-source-lbip-basic.cassette.yaml
- scaleway/testdata/rdb-read-replica-basic.cassette.yaml
- scaleway/testdata/rdb-read-replica-different-zone.cassette.yaml
- scaleway/testdata/rdb-read-replica-multiple-endpoints.cassette.yaml
- scaleway/testdata/rdb-read-replica-private-network.cassette.yaml
- scaleway/testdata/rdb-read-replica-update.cassette.yaml
> feat(rdb): read replica: fill empty values in import generation

- docs/resources/container_cron.md
- scaleway/resource_container_cron.go
- scaleway/resource_container_cron_test.go
- scaleway/testdata/container-cron-basic.cassette.yaml
- scaleway/testdata/container-cron-with-multi-args.cassette.yaml
> feat(container_cron): add name

- scaleway/helpers_rdb.go
- scaleway/resource_rdb_read_replica.go
- scaleway/resource_rdb_read_replica_test.go
- scaleway/testdata/rdb-read-replica-basic.cassette.yaml
- scaleway/testdata/rdb-read-replica-different-zone.cassette.yaml
- scaleway/testdata/rdb-read-replica-multiple-endpoints.cassette.yaml
- scaleway/testdata/rdb-read-replica-private-network.cassette.yaml
- scaleway/testdata/rdb-read-replica-update.cassette.yaml
This PR follows up #2308 (which updates the handling of endpoints for instances) and update endpoint management in read replicas.
> fix(rdb): read replica: endpoints management

- scaleway/helpers_cockpit.go
- scaleway/resource_cockpit.go
- scaleway/resource_cockpit_test.go
- scaleway/testdata/cockpit-basic.cassette.yaml
close https://github.com/scaleway/terraform-provider-scaleway/issues/2062
> feat(cockpit) : add push_url in cockpit ressource

- scaleway/resource_k8s_cluster.go
The provider returns the same error message if the form of the `version` attribute (minor `x.y` or patch `x.y.z`) is inconsistent with whether or not `auto_upgrade` is enabled, and it leads to confusion for some users as reported in the Scaleway Community Slack.
This PR makes the provider return 2 error messages:
- one for the case: auto_upgrade=true && version=x.y.z
- one for the case: auto_upgrade=false && version=x.y
> feat(k8s): minor version error messages are more precise

- scaleway/resource_instance_server.go
- scaleway/testdata/data-source-ipamip-instance-lb.cassette.yaml
- scaleway/testdata/data-source-ipamip-instance.cassette.yaml
- scaleway/testdata/data-source-vpc-public-gateway-dhcp-reservation-basic.cassette.yaml
- scaleway/testdata/data-source-vpc-public-gateway-dhcp-reservation-static.cassette.yaml
- scaleway/testdata/instance-image-server-with-block-volume.cassette.yaml
- scaleway/testdata/instance-image-server-with-local-volume.cassette.yaml
- scaleway/testdata/instance-image-server.cassette.yaml
- scaleway/testdata/instance-server-block-external.cassette.yaml
- scaleway/testdata/instance-server-ip-migrate.cassette.yaml
- scaleway/testdata/instance-server-ip-removed.cassette.yaml
- scaleway/testdata/instance-server-private-network.cassette.yaml
- scaleway/testdata/instance-server-routed-ip-enable-with-ip.cassette.yaml
- scaleway/testdata/instance-server-routed-ip-enable.cassette.yaml
- scaleway/testdata/instance-server-with-reserved-ip.cassette.yaml
- scaleway/testdata/instance-snapshot-server-with-block-volume.cassette.yaml
- scaleway/testdata/instance-snapshot-server.cassette.yaml
- scaleway/testdata/lblb-with-private-networks-on-dhcp-config.cassette.yaml
- scaleway/testdata/vpc-public-gateway-dhcp-entry-basic.cassette.yaml
- scaleway/testdata/vpc-public-gateway-pat-rule-with-instance.cassette.yaml
- scaleway/validate_cassettes_test.go
This allow the terraform provider to rely on API's default for this field.
Resource `scaleway_instance_ip` already used API's default for its type.
> fix(instance_server): default routed_ip_enabled to nil

- scaleway/data_source_ipam_ip.go
- scaleway/helpers_ipam.go
This PR introduces a retry mechanism, specifically targeting scenarios where an initial API call returns an empty IP list. An empty response can occasionally occur due to propagation delays
> feat(ipam): add retry on empty IP list

- docs/resources/rdb_instance.md
- docs/resources/rdb_read_replica.md
- scaleway/data_source_ipam_ip_test.go
- scaleway/helpers_rdb.go
- scaleway/resource_rdb_instance.go
- scaleway/resource_rdb_instance_test.go
- scaleway/resource_rdb_read_replica.go
- scaleway/resource_rdb_read_replica_test.go
- scaleway/testdata/data-source-ipamiprdb.cassette.yaml
- scaleway/testdata/rdb-instance-endpoints.cassette.yaml
- scaleway/testdata/rdb-instance-private-network-dhcp.cassette.yaml
- scaleway/testdata/rdb-instance-private-network-update.cassette.yaml
- scaleway/testdata/rdb-instance-private-network.cassette.yaml
- scaleway/testdata/rdb-read-replica-basic.cassette.yaml
- scaleway/testdata/rdb-read-replica-different-zone.cassette.yaml
- scaleway/testdata/rdb-read-replica-multiple-endpoints.cassette.yaml
- scaleway/testdata/rdb-read-replica-private-network.cassette.yaml
- scaleway/testdata/rdb-read-replica-update.cassette.yaml
- scaleway/testdata/rdb-read-replica-with-instance-also-in-private-network.cassette.yaml
This PR renders the choice between a static configuration (with given IPs) and IPAM configuration explicit when creating a private endpoint for Read Replicas and Instances.
It also fixes the error `expected no more than 1 IP for instance, got 2` which occurred when more than 1 RDB resource (for example 1 Instance + 1 Read Replica) was attached to the same Private Network.
Closes #2399
> fix(rdb): explicit choice for endpoint IP configuration in Read Replica and Instance

- scaleway/resource_redis_cluster_test.go
- scaleway/testdata/redis-cluster-migrate-cluster-size-with-static-endpoint.cassette.yaml
The Redis nightly tests failed because of an error during the creation of the private network (`subnets is invalid for unexpected reason, subnet_overlaps_in_vpc: {}`), removing said subnet from the configuration may resolve the issue as it is not mandatory.
> test(redis): remove subnet from vpc to avoid `subnet overlap in vpc`

- scaleway/resource_object_bucket.go
- scaleway/resource_object_bucket_test.go
- scaleway/testdata/object-bucket-lifecycle.cassette.yaml
> fix(object): lifecycle rules: fix parsing error when prefix+1tag set

- docs/resources/job_definition.md
> docs(job_defintion): add cron

- scaleway/resource_rdb_instance.go
- scaleway/resource_rdb_instance_test.go
- scaleway/testdata/rdb-instance-volume.cassette.yaml
I noticed a case that did not occur in the tests but there was a bug when changing the volume type from `bssd` to `lssd` as the `volume_size_in_gb` attribute goes from the given value to 0 (the volume size depends on the node type). And since we carry out the upgrades starting from the volume and ending with the node type, that resulted in the API rejecting the update of the `volume_type` because the `node_type` should be updated first.
To fix the issue, this PR adds the comparing of the actual and the wanted storage capacities to see if the node_type has to be updated first.
> fix(rdb): allow updates from bssd to lssd if new node type has enough space

- scaleway/helpers.go
- scaleway/helpers_rdb.go
- scaleway/helpers_test.go
- scaleway/resource_lb_backend.go
- scaleway/testdata/rdb-instance-volume.cassette.yaml
- scaleway/testdata/test-acc-get-raw-config-for-key.cassette.yaml
Closes #2418 
Needs #2461 first
> feat(core): get raw config for key

- internal/services/k8s/k8s_version_data_source_test.go
- internal/services/k8s/testdata/data-source-version-basic.cassette.yaml
Will fix [this](https://github.com/scaleway/terraform-provider-scaleway/actions/runs/8592880246/job/23543532454#step:4:1115) error in the k8s nightly tests.
> test(k8s): add cni=none to expected in version data source test

- internal/meta/extractors.go
- internal/services/lb/backend.go
- internal/services/lb/helpers_lb.go
- internal/services/rdb/helpers.go
This function's integration was lost in the refactoring.
> chore: move GetRawConfigForKey function to meta package

- docs/resources/tem_domain_validation.md
- internal/provider/provider.go
- internal/services/tem/domain_validation.go
- internal/services/tem/domain_validation_test.go
- internal/services/tem/helpers.go
- internal/services/tem/testdata/data-source-domain-basic.cassette.yaml
- internal/services/tem/testdata/data-source-domain-reputation.cassette.yaml
- internal/services/tem/testdata/domain-basic.cassette.yaml
- internal/services/tem/testdata/domain-tos.cassette.yaml
- internal/services/tem/testdata/domain-validation-no-validation.cassette.yaml
- internal/services/tem/testdata/domain-validation-validation.cassette.yaml
> feat(tem) : add ressource for validate tem domain

- docs/resources/instance_server.md
- internal/services/instance/server.go
- internal/services/instance/server_test.go
`enable_ipv6` will always be disabled without routed_ip enabled
> fix(instance_server): ignore enable_ipv6 with routed_ip disabled

- docs/resources/ipam_ip.md
Using specific IPs may lead to conflicts with automatically-allocated IPs by IPAM, blocking further progression of the terraform plan.
This adds an outline of the issue, and some recommendations on how to work around it.
> docs/ipam: add warning on the use of client-defined IPs

- go.mod
- go.sum
- internal/services/object/bucket.go
- internal/services/object/bucket_acl.go
- internal/services/object/bucket_acl_test.go
- internal/services/object/bucket_lock_configuration.go
- internal/services/object/bucket_policy.go
- internal/services/object/bucket_website_configuration.go
- internal/services/object/data_source_object_bucket.go
- internal/services/object/data_source_object_bucket_policy.go
- internal/services/object/helpers_object.go
- internal/services/object/testdata/object-bucket-acl-basic.cassette.yaml
- internal/services/object/testdata/object-bucket-acl-grantee-with-owner.cassette.yaml
- internal/services/object/testdata/object-bucket-acl-grantee.cassette.yaml
- internal/services/object/testdata/object-bucket-acl-remove.cassette.yaml
- internal/services/object/testdata/object-bucket-acl-with-bucket-name.cassette.yaml
- internal/services/object/testdata/object-bucket-lock-configuration-basic.cassette.yaml
- internal/services/object/testdata/object-bucket-lock-configuration-update.cassette.yaml
- internal/services/object/testdata/object-bucket-lock-configuration-with-bucket-name.cassette.yaml
> fix(object): acl: revert bucket acl to private on resource deletion

- internal/logging/logger.go
This fix the need of `SCW_DEBUG=1` to get requests logs. Only `TF_LOG=DEBUG` is needed with this change.
This logger was made to replace the sdk logger as specified in logger.Logger docstring.
> fix(logger): set provider logger as sdk-go logger

- internal/services/instance/helpers_instance.go
- internal/services/instance/server.go
- internal/services/instance/server_test.go
- internal/services/instance/testdata/server-private-network-missing-pnic.cassette.yaml
If a private nic is deleted while it was managed by terraform using `scaleway_instance_server.private_network`, it will make terraform get stuck on each refresh or apply.
> fix(instance): server private_network with deleted pnic

- .gitignore
- examples/instance-servers/README.md
- examples/instance-servers/main.tf
- examples/instance-servers/outputs.tf
- examples/instance-servers/variables.tf
Init a new examples folder. Examples will be tested by CI in the future
> docs: add instance example

- docs/resources/mnq_nats_account.md
- docs/resources/mnq_nats_credentials.md
- docs/resources/mnq_sns.md
- docs/resources/mnq_sns_credentials.md
- docs/resources/mnq_sns_topic.md
- docs/resources/mnq_sns_topic_subscription.md
- docs/resources/mnq_sqs.md
- docs/resources/mnq_sqs_credentials.md
- docs/resources/mnq_sqs_queue.md
This PR reviews the Messaging and Queuing Terraform doc, and suggests small corrections for grammar, capitalization and outdated links.
> fix(mnq): doc review of terraform mnq doc

- internal/services/container/testdata/domain-basic.cassette.yaml
- internal/services/domain/record.go
- internal/services/domain/testdata/data-source-domain-record-basic.cassette.yaml
- internal/services/domain/testdata/data-source-domain-zone-basic.cassette.yaml
- internal/services/domain/testdata/domain-record-arobase.cassette.yaml
- internal/services/domain/testdata/domain-record-basic.cassette.yaml
- internal/services/domain/testdata/domain-record-basic2.cassette.yaml
- internal/services/domain/testdata/domain-record-cname.cassette.yaml
- internal/services/domain/testdata/domain-record-geo-ip.cassette.yaml
- internal/services/domain/testdata/domain-record-http-service.cassette.yaml
- internal/services/domain/testdata/domain-record-srv-zone.cassette.yaml
- internal/services/domain/testdata/domain-record-view.cassette.yaml
- internal/services/domain/testdata/domain-record-weighted.cassette.yaml
- internal/services/domain/testdata/domain-zone-basic.cassette.yaml
- internal/services/domain/zone.go
- internal/services/domain/zone_test.go
- internal/services/function/testdata/function-domain-basic.cassette.yaml
- internal/services/instance/testdata/ip-reverse-dns-basic.cassette.yaml
- internal/services/ipam/testdata/ipamip-reverse-dns-basic.cassette.yaml
- internal/services/tem/testdata/domain-validation-validation.cassette.yaml
- internal/services/vpcgw/testdata/vpc-public-gateway-ip-reverse-dns-basic.cassette.yaml
potential fix [#2508](https://github.com/scaleway/terraform-provider-scaleway/issues/2508)
> fix: update deprecated dns_zone field

- internal/services/function/cron_test.go
- internal/services/function/data_source_function_test.go
- internal/services/function/domain_test.go
- internal/services/function/function.go
- internal/services/function/function_test.go
- internal/services/function/testdata/data-source-function-basic.cassette.yaml
- internal/services/function/testdata/function-basic.cassette.yaml
- internal/services/function/testdata/function-cron-basic.cassette.yaml
- internal/services/function/testdata/function-cron-name-update.cassette.yaml
- internal/services/function/testdata/function-cron-with-args.cassette.yaml
- internal/services/function/testdata/function-deploy.cassette.yaml
- internal/services/function/testdata/function-domain-basic.cassette.yaml
- internal/services/function/testdata/function-environment-variables.cassette.yaml
- internal/services/function/testdata/function-http-option.cassette.yaml
- internal/services/function/testdata/function-no-name.cassette.yaml
- internal/services/function/testdata/function-timeout.cassette.yaml
- internal/services/function/testdata/function-token-basic.cassette.yaml
- internal/services/function/testdata/function-trigger-nats.cassette.yaml
- internal/services/function/testdata/function-trigger-sqs.cassette.yaml
- internal/services/function/testdata/function-upload.cassette.yaml
- internal/services/function/token_test.go
- internal/services/function/trigger_test.go
Bumps default `memory_limit` to align with the Scaleway Console
> chore(function): bump default memory limit

- docs/data-sources/iam_api_key.md
- internal/provider/provider.go
- internal/services/iam/api_key_data_source.go
- internal/services/iam/api_key_data_source_test.go
- internal/services/iam/testdata/data-source-api-key-basic.cassette.yaml
> feat(iam_api_key): add data source

- docs/data-sources/container.md
- docs/resources/container.md
- docs/resources/function.md
- internal/services/container/container.go
- internal/services/container/container_test.go
- internal/services/container/helpers_container.go
- internal/services/container/testdata/container-sandbox.cassette.yaml
- internal/services/function/function.go
- internal/services/function/function_test.go
- internal/services/function/testdata/function-sandbox.cassette.yaml
> feat(serverless): add sandbox field

- internal/services/lb/ips_data_source_test.go
- internal/services/lb/testdata/data-source-ips-with-type.cassette.yaml
Moved resources to another zone to avoid unexpected ip count from the other tests
> tests(lb): fix unexpected ip count

- docs/data-sources/secret_version.md
- internal/services/secret/testdata/data-source-secret-version-basic.cassette.yaml
- internal/services/secret/testdata/data-source-secret-version-by-name-secret.cassette.yaml
- internal/services/secret/version_data_source_test.go
> tests(secret_version): datasource using latest revision

- docs/resources/secret.md
- internal/acctest/validate_cassettes_test.go
- internal/services/secret/helpers.go
- internal/services/secret/secret.go
- internal/services/secret/secret_test.go
- internal/services/secret/testdata/secret-protected.cassette.yaml
> feat(secret): add protected field

- docs/resources/cockpit_source.md
- internal/services/cockpit/cockpit.go
- internal/services/cockpit/cockpit_data_source.go
- internal/services/cockpit/cockpit_test.go
- internal/services/cockpit/helpers_cockpit.go
- internal/services/cockpit/source.go
- internal/services/cockpit/source_test.go
- internal/services/cockpit/testdata/cockpit-alert-manager-create-with-multiple-contacts.cassette.yaml
- internal/services/cockpit/testdata/cockpit-alert-manager-create-with-single-contact.cassette.yaml
- internal/services/cockpit/testdata/cockpit-alert-manager-enable-disable.cassette.yaml
- internal/services/cockpit/testdata/cockpit-alert-manager-update-single-contact.cassette.yaml
- internal/services/cockpit/testdata/cockpit-basic.cassette.yaml
- internal/services/cockpit/testdata/cockpit-source-basic-logs.cassette.yaml
- internal/services/cockpit/testdata/cockpit-source-basic-metrics.cassette.yaml
- internal/services/cockpit/testdata/cockpit-source-basic.cassette.yaml
- internal/services/cockpit/testdata/cockpit-with-source-endpoints.cassette.yaml
- internal/services/cockpit/testdata/data-source-cockpit-basic.cassette.yaml
- internal/services/cockpit/testdata/data-source-cockpit-plan-basic.cassette.yaml
- internal/services/cockpit/testdata/grafana-user-basic.cassette.yaml
- internal/services/cockpit/testdata/grafana-user-update.cassette.yaml
- internal/services/cockpit/testdata/token-basic.cassette.yaml
- internal/services/cockpit/testdata/token-no-scopes.cassette.yaml
- internal/services/cockpit/testdata/token-update.cassette.yaml
- internal/services/cockpit/types.go
close [#2563](https://github.com/scaleway/terraform-provider-scaleway/issues/2563)
> feat:(cockpit): add push urls to cockpit datasources

- internal/services/applesilicon/waiters.go
**Problem occured**:
While trying to create a M2-L server using Terraform and the Scaleway provider, I got a timeout after 2 minutes which seems short for a server creation. With a timeout this short, it makes the developer experience quite bad because the Apple Silicon's server needs to be used at least an entire day (24 hours) before I can destroy them.
**Solutions**:
I found 2 solutions, 1 short term and 1 long term. Here there are:
1. **Short term**: We can fix this issue easily by adding this piece of code in the `scaleway_apple_silicon_server` resource:
```
resource scaleway_apple_silicon_server "server" {
...
timeouts {
create = "20m" 
}
...
}
```
2. **Long term**: We can also just increase the duration of the timeout to 20 minutes, the default for a creation in Terraform (source …
> fix(apple-silicon): increase timeout for server creation

- .golangci.yml
WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.
> chore: remove exportloopref

- internal/services/rdb/instance.go
close [#1377](https://github.com/scaleway/terraform-provider-scaleway/issues/1377)
> fix(rdb): migrate endpoint to endpoints

- internal/services/secret/helpers.go
- internal/services/secret/secret_data_source.go
- internal/services/secret/testdata/data-source-secret-version-basic.cassette.yaml
- internal/services/secret/version_data_source.go
- internal/services/secret/version_data_source_test.go
> fix(secret): set project_id as optional in datasources

- internal/services/account/helpers.go
- internal/services/account/project.go
> fix(account_project): retry delete when project is not usable

- internal/services/instance/helpers_instance_block.go
- internal/services/instance/server.go
- internal/services/instance/server_test.go
- internal/services/instance/testdata/private-nic-with-ipam.cassette.yaml
- internal/services/instance/testdata/server-block-external-root-volume.cassette.yaml
- internal/services/instance/testdata/server-root-volume1.cassette.yaml
> feat(instance_server): allow root_volume size update

- internal/services/instance/server.go
Instance API currently miss zone when returning sbs volumes
Linked to https://github.com/scaleway/scaleway-sdk-go/issues/2273
> fix(instance_server): use server volume to fetch volumes

- internal/services/mnq/nats_credentials.go
Currently, when creating NATS credentials, the field 'file' is not marked as sensitive. While it does not cause issue during creation since this value is not yet computed, it causes issue during deletion where the secret is leaked:
```
- resource "scaleway_mnq_nats_credentials" "key-manager" {
- account_id = (sensitive value) -> null
- file       = <<-EOT
-----BEGIN NATS USER JWT-----
XXX REDACTED XXX
------END NATS USER JWT------
************************* IMPORTANT *************************
NKEY Seed printed below can be used to sign and prove identity.
NKEYs are sensitive and should be treated as secrets.
-----BEGIN USER NKEY SEED-----
XXX REDACTED XXX
------END USER NKEY SEED------
*************************************************************
EOT -> null
- id         = "REDACTED" -> …
```
> fix(mnq): mark field 'file' as sensitive

- docs/resources/instance_server.md
- docs/resources/lb.md
Provide details for ressources `scaleway_instance_server` and `scaleway_lb`.
> doc: usage clarification

- go.mod
- go.sum
- internal/services/container/namespace.go
- internal/services/container/namespace_test.go
- internal/services/container/testdata/namespace-basic.cassette.yaml
- internal/services/function/namespace.go
- internal/services/function/namespace_test.go
- internal/services/function/testdata/function-namespace-basic.cassette.yaml
Hello,
Go SDK now supports tags on functions and container namespaces since https://github.com/scaleway/scaleway-sdk-go/commit/2a48843b5fcba4ab5624b25ebe1dc79cae5fdac1 (hence the bump in `go.mod`). This PR adds support in Terraform for these fields in both functions and containers namespaces.
:warning: please wait 2024/11/19 before merging, but this doesn't prevent from reviewing :warning:
Tested with a local build of the provider and the following config:
```hcl
resource "scaleway_container_namespace" "main" {
name = "test"
tags = ["tag1", "tag2"]
}
resource "scaleway_function_namespace" "main" {
name = "test"
tags = ["tag1", "tag2", "tag3"]
}
```
After `terraform apply`ing, tags are added to the namespaces.
For containers:
```shell
$ curl -s -H "X-Auth-Token: $SCW_SECRET_KEY" …
```
> feat(serverless): add support for tags on functions/containers namespaces

- docs/resources/instance_server.md
- internal/services/instance/server.go
- internal/services/instance/server_test.go
- internal/services/instance/testdata/server-block-external-root-volume.cassette.yaml
- internal/services/instance/testdata/server-root-volume1.cassette.yaml
> fix(instance_server): allow updating root_volume size for non l_ssd

- docs/resources/cockpit_source.md
- internal/services/cockpit/cockpit_data_source_test.go
- internal/services/cockpit/source.go
- internal/services/cockpit/source_test.go
- internal/services/cockpit/testdata/cockpit-source-basic-logs.cassette.yaml
- internal/services/cockpit/testdata/cockpit-source-basic-metrics.cassette.yaml
- internal/services/cockpit/testdata/cockpit-source-retention-days.cassette.yaml
- internal/services/cockpit/testdata/cockpit-source-update.cassette.yaml
- internal/services/cockpit/testdata/data-source-cockpit-basic.cassette.yaml
fix [#2844](https://github.com/scaleway/terraform-provider-scaleway/issues/2844)
> feat(cockpit): add retention days in resource source

- docs/resources/instance_server.md
- internal/services/instance/server.go
> doc(instance_server): mark private_ip as deprecated

- docs/resources/vpc_public_gateway_dhcp.md
It's now recommend to use IPAM
> docs(vpc): add a warning about push_default_route

- docs/data-sources/container.md
- docs/resources/container.md
- internal/services/container/container.go
- internal/services/container/container_data_source_test.go
- internal/services/container/container_test.go
- internal/services/container/helpers_container.go
- internal/services/container/testdata/container-scaling-option.cassette.yaml
- internal/services/container/testdata/data-source-container-scaling-option.cassette.yaml
A new ScalingOption object was added to containers. It replace current max_concurrency. The old field should be marked as deprecated while adding the new object.
API Reference: https://www.scaleway.com/en/developers/api/serverless-containers/#path-containers-create-a-new-container
* scaleway_container
```terraform
resource scaleway_container main {
namespace_id = scaleway_container_namespace.main.id
deploy = false
scaling_option {
concurrent_requests_threshold = 15
}
}
```
* https://github.com/scaleway/terraform-provider-scaleway/issues/2811
* https://github.com/scaleway/terraform-provider-scaleway/issues/2812
* Using `scaling_option` terraform configuration to be compliant with the API.
* Acceptance tests from real calls have been created on both resource and data.
* Documentation has …
> feat(containers): add scaling_option block

- internal/services/instance/server.go
This is the last step before forced migration. If forced migration happens and users have `b_ssd` set explicitly in their tf config, their servers will get replaced (ForceNew).
> feat(instance): prevent explicit b_ssd usage for server root_volume

- internal/services/domain/record.go
- internal/services/domain/record_test.go
- internal/services/domain/testdata/data-source-domain-record-basic.cassette.yaml
- internal/services/domain/testdata/data-source-domain-zone-basic.cassette.yaml
- internal/services/domain/testdata/domain-record-arobase.cassette.yaml
- internal/services/domain/testdata/domain-record-basic.cassette.yaml
- internal/services/domain/testdata/domain-record-basic2.cassette.yaml
- internal/services/domain/testdata/domain-record-cname.cassette.yaml
- internal/services/domain/testdata/domain-record-geo-ip.cassette.yaml
- internal/services/domain/testdata/domain-record-http-service.cassette.yaml
- internal/services/domain/testdata/domain-record-srv-zone.cassette.yaml
- internal/services/domain/testdata/domain-record-view.cassette.yaml
- internal/services/domain/testdata/domain-record-weighted.cassette.yaml
- internal/services/domain/testdata/domain-zone-basic.cassette.yaml
close [2873](https://github.com/scaleway/terraform-provider-scaleway/issues/2873)
> fix(domain): ensure scaleway_domain_record updates on apply

- docs/index.md
The current doc use `TF_LOG=WARN`, it does not show requests.
> docs: set TF_LOG=DEBUG in deployment debugging

- docs/data-sources/lb_backends.md
- docs/resources/lb_backend.md
The `uri` parameter takes a path, not a full URI. Otherwise, the health check doesn't work and the servers are always reported as down.
> docs(lb): clarify health check URI description

- internal/services/container/helpers_container.go
- internal/services/container/namespace.go
- internal/services/container/namespace_test.go
- internal/services/container/testdata/namespace-basic.cassette.yaml
- internal/services/container/testdata/namespace-secret-management.cassette.yaml
> fix(container): fix secret management container

- docs/data-sources/tem_offer_subscription.md
- internal/provider/provider.go
- internal/services/tem/helpers.go
- internal/services/tem/offer_subscription_data_source.go
- internal/services/tem/offer_subscription_data_source_test.go
- internal/services/tem/testdata/data-source-domain-basic.cassette.yaml
- internal/services/tem/testdata/data-source-offer-subscription-basic.cassette.yaml
close [#2963](https://github.com/scaleway/terraform-provider-scaleway/issues/2963)
> feat(tem): add data_source for offer subscription

- docs/resources/k8s_pool.md
Adjust documentation to match code
https://github.com/scaleway/terraform-provider-scaleway/blob/f5d4aa65717c1fd9f4c18d5e29112df9a16420ad/internal/services/k8s/pool.go#L101-L106
> docs: correct `wait_for_pool_ready` default value in documentation

- internal/services/function/function.go
Hello :wave:
Just a small fix :bug:
When a function `runtime` is updated from Terraform:
1. the `runtime` field was actually not updated (e.g. when we `GET` from the API): this is because this case is simply not handled in the existing code
2. the function is not redeployed. When changing runtime, even if `deploy` is `false`, I think most users expect their function to be rebuilt with the new runtime (e.g. when bumping from `python310` to `python313`)
If 2. is controversial, maybe we can just replace:
```diff
-	shouldDeploy = shouldDeploy || d.HasChange("runtime")
+	shouldDeploy = shouldDeploy || (d.HasChange("runtime") && deploy)
```
So, runtime is changed, but function is not redeployed unless **explicitly** told to do so.
`main.tf`:
```hcl
data "archive_file" "source_zip" {
type …
```
> fix(functions): update function when runtime has changed and redeploy

- docs/resources/rdb_instance.md
- docs/resources/rdb_snapshot.md
close [#2975](https://github.com/scaleway/terraform-provider-scaleway/issues/2975)
> docs(rdb_snapshot): remove unsupported snapshot_id argument

- docs/resources/k8s_acl.md
- internal/provider/provider.go
- internal/services/k8s/acl.go
- internal/services/k8s/acl_test.go
- internal/services/k8s/testdata/acl-basic.cassette.yaml
> feat(k8s): add cluster ACLs

- internal/services/edgeservices/testfuncs/sweep.go
fixes https://github.com/scaleway/terraform-provider-scaleway/actions/runs/14698141826/job/41244881374
When the `-sweep` flag is passed, the sweep function are ran by the Terraform SDK, and the edgeservices one are using a wrong method to instantiate the client which cause a panic
```
panic: interface conversion: interface {} is *scw.Client, not *meta.Meta
goroutine 1 [running]:
github.com/scaleway/terraform-provider-scaleway/v2/internal/meta.ExtractScwClient(...)
/home/runner/work/terraform-provider-scaleway/terraform-provider-scaleway/internal/meta/extractors.go:97
github.com/scaleway/terraform-provider-scaleway/v2/internal/services/edgeservices.NewEdgeServicesAPI(...)
/home/runner/work/terraform-provider-scaleway/terraform-provider-scaleway/internal/services/edgeservices/helpers.go:12 …
```
> Fix nightly sweep 

- internal/services/instance/server.go
For the end of service warning message to be clearer, we should only display the 5 most relevant Instance types, and redirect users to the CLI for the full list. The warning will be displayed as follows :
```
╷
│ Warning: Your Instance will soon reach End of Service. You can check the exact date on the Scaleway console. We recommend that you migrate your Instance before that.
│ Here are the 5 best options for "ENT1-S", ordered by relevance: [POP2-8C-32G, POP2-2C-8G, POP2-4C-16G, POP2-16C-64G, POP2-32C-128G]
│ 
│ You can check the full list of compatible server types:
│       - on the Scaleway console
│       - using the CLI command 'scw instance server get-compatible-types e957d3cb-8b5a-4881-804b-4ac1b612b3e3 zone=fr-par-1'
│ 
│   with scaleway_instance_server.eos,
│   on endofservice.tf …
```
> fix(instance): EoS warning should only display the 5 most relevant types

- docs/resources/rdb_instance.md
- internal/services/ipam/testdata/data-source-ipamiprdb.cassette.yaml
- internal/services/rdb/instance.go
- internal/services/rdb/instance_test.go
- internal/services/rdb/testdata/instance-endpoints.cassette.yaml
- internal/services/rdb/testdata/instance-private-network-update.cassette.yaml
- internal/services/rdb/testdata/read-replica-with-instance-also-in-private-network.cassette.yaml
This PR adds the `private_ips` exported field to the RDB Instance resource schema.
Left to-do:
> feat(rdb): read instance private ips

- docs/data-sources/account_projects.md
- internal/provider/provider.go
- internal/services/account/project_data_source.go
- internal/services/account/project_data_source_test.go
- internal/services/account/testdata/data-source-project-list.cassette.yaml
Example terraform
```
locals {
public_key = "ssh-xxxx"
}
resource "scaleway_iam_ssh_key" "test" {
name       = "main"
public_key = local.public_key
count      = length(data.scaleway_account_projects.test.projects)
project_id = data.scaleway_account_projects.test.projects[count.index].id
}
```
fixes https://github.com/scaleway/terraform-provider-scaleway/issues/3078
> feat(project): add the projects datasource

- docs/resources/iam_user.md
- internal/services/iam/testdata/user-guest.cassette.yaml
- internal/services/iam/testdata/user-member.cassette.yaml
- internal/services/iam/user.go
- internal/services/iam/user_test.go
This Pull Request implements the feature requested in the issue #3021
> feat(iam): creation of user as Member

- docs/resources/container.md
- docs/resources/container_namespace.md
- docs/resources/function.md
- docs/resources/function_namespace.md
- internal/services/container/container.go
- internal/services/container/container_test.go
- internal/services/container/helpers_container.go
- internal/services/container/testdata/container-basic.cassette.yaml
- internal/services/function/function.go
- internal/services/function/function_test.go
- internal/services/function/testdata/function-basic.cassette.yaml
> feat(serverless): add tags to container and function resources

- internal/acctest/acctest.go
- internal/acctest/acctest_test.go
- internal/acctest/compare.go
- internal/acctest/vcr.go
When comparing a json request body with the cassette ones, if the json dict is nested, like in such case :
```
{
"organization_id": "6867048b-fe12-4e96-835e-41c79a39604b",
"tags": [
"bar"
],
"member": {
"email": "bar@scaleway.com",
"send_password_email": false,
"send_welcome_email": false,
"username": "bar",
"password": "",
"first_name": "",
"last_name": "",
"phone_number": "",
"locale": ""
}
}
```
The comparison will return true even if the nested values are different (values inside the "member" key)
This lead to behavior such as constant Terraform drift when attempting to replay some query, in particular when creating  different objects with nested values like `scaleway_iam_user` https://github.com/scaleway/terraform-provider-scaleway/pull/3126/files#diff-23bcf61d4790cd7c6dff0968222979dc …
>  fix(acctest): compare in depth request body with cassette body 

- docs/resources/object_bucket_acl.md
- internal/services/object/bucket_acl.go
- internal/services/object/bucket_acl_test.go
- internal/services/object/object.go
- internal/services/object/testdata/object-bucket-acl-grantee-with-owner.cassette.yaml
- internal/services/object/testdata/object-bucket-acl-grantee.cassette.yaml
fix https://github.com/scaleway/terraform-provider-scaleway/issues/3119
> feat(object): support the group bucket ACL

- docs/resources/instance_server.md
- internal/services/instance/server.go
- internal/services/instance/server_test.go
- internal/services/instance/testdata/server-ips.cassette.yaml
- internal/services/instance/types.go
> feat(instance): server: add more fields on public_ips

- docs/resources/mongodb_user.md
- internal/provider/provider.go
- internal/services/mongodb/helpers.go
- internal/services/mongodb/testdata/mongo-db-user-basic.cassette.yaml
- internal/services/mongodb/testdata/mongo-db-user-state-import.cassette.yaml
- internal/services/mongodb/user.go
- internal/services/mongodb/user_test.go
- templates/resources/mongodb_user.md.tmpl
close [#3224](https://github.com/scaleway/terraform-provider-scaleway/issues/3224)
> feat(mongodb): implement user resource with role management

- templates/resources/rdb_instance.md.tmpl
close [#3223](https://github.com/scaleway/terraform-provider-scaleway/issues/3223)
> docs(rdb): update VPC routing compatibility note
